### ISSUE TITLE
clockfs broken

### ISSUE THREAD

**Issue by anonopete** [bazil/fuse#105]
darwin 10.10.4, clean install (go 1.4.2, new bazil/fuse as of 9/20.

Running clockfs is fine until I access the clock file. For example:

  titan:~> cat /tmp/dss/clock
  5	2015-07-20 11:31:32.552904699 -0400 EDT

results in error messages:

titan:~/go/src/bazil.org/fuse/examples/clockfs> go run clockfs.go /tmp/dss                                                                                    2015/07/20 11:31:33 invalidate error: invalid argument
2015/07/20 11:31:34 invalidate error: invalid argument
2015/07/20 11:31:35 invalidate error: invalid argument
2015/07/20 11:31:36 invalidate error: invalid argument
2015/07/20 11:31:37 invalidate error: invalid argument
2015/07/20 11:31:38 invalidate error: invalid argument
2015/07/20 11:31:39 invalidate error: invalid argument

**Comment by tv42** [comment]
The larger examples are sadly not currently automatically tested, and sometimes lag a few API changes behind. Will fix..

**Comment by tv42** [comment]
Sorry for the delay, finally got back around to this.

clockfs isn't really broken, there; OSXFUSE 2.x doesn't support invalidations, so a demo of invalidations cannot work there.

**Comment by anonopete** [comment]
I just noticed that invalidate is in the code base:
   https://github.com/bfleischer/fuse-macosx/blob/master/lib/fuse_lowlevel.c

Will this make it into at least a beta in the near future?

Thanks,
pete

**Comment by tv42** [comment]
Hey, sorry for the delay in responding, didn't really notice this question in a closed ticket.

OSXFUSE 3.x is in beta and support invalidation. Whether you want to run a beta version is up to you; the latest version seems to work about as well as 2.8.0, for me.

And for the record, OSXFUSE is at https://github.com/osxfuse/osxfuse

**Comment by anonopete** [comment]
The mac osxfuse (at 2.8.1) control panel doesn't show any beta versions,
even w/ the box checked.

Where can I find this?

Thanks,
pete

**Comment by tv42** [comment]
You should talk to the OSXFUSE project about OSXFUSE.

https://github.com/osxfuse/osxfuse/releases
