### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by kunal** [bazil/fuse#108]
When I do "go get bazil.org/fuse" I get an error:
**package bazil.org/fuse: unrecognized import path "bazil.org/fuse"**

**Comment by tv42** [comment]
What does `go version` output?

**Comment by kunal** [comment]
go version go1.2.1 linux/amd64

**Comment by tv42** [comment]
That's too old to be useful. Upgrade to Go 1.4. http://golang.org/doc/install
