### ISSUE TITLE
hellofs hanging on osx

### ISSUE THREAD

**Issue by icexin** [bazil/fuse#110]
go version 1.5rc1, osx 10.10.4, OSXFUSE 2.8.0

**Comment by jabalsad** [comment]
I have a similar issue. However, while it is "running", the mounted filesystem works as expected. When sending SIGINT to terminate the application, there is a dangling osxfuse mount that I need to manually unmount using `sudo umount $mountpoint`.

I tried to install a signal handler that explicitly calls c.Close(), but then sending SIGINT results in the application just hanging. Force un-mounting the mount point unblocks the application and it exits.

**Comment by tv42** [comment]
@jabalsad You shouldn't need `sudo` for that unmount, but that's considered the right design. If you let app dying unmount it automatically, then users of the filesystem might accidentally start creating files in the underlying filesystem.

Not sure if that's related to the reported hang in any way.

**Comment by jabalsad** [comment]
Please excuse my ignorance :-) I'm still learning the intended behaviour of this library. Of course, the application will have to stay open in order to handle requests to that mountpoint. I guess (for experiments' sake) I just need to learn how to clean up a mount point when the application exits. I'm not sure `c.Close()` is the way to do that.

**Comment by jabalsad** [comment]
A little bit of experimentation lead me to `fuse.Unmount()`. Therefore, please ignore my previous comments :)

**Comment by tv42** [comment]
The unmount thing isn't about this library, it's about FUSE in general. `fuse.Unmount` is a convenience function that calls `fusermount` or `umount` (depending on platform) as a subprocess.

**Comment by tv42** [comment]
Can't reproduce this, and the bug contains nothing useful to go on. If it still happens for you, reopen and include `hellofs -fuse.debug` output.
