### ISSUE TITLE
Loopback FS can't open/edit/save excel file

### ISSUE THREAD

**Issue by elgutierrez** [bazil/fuse#116]
Hello,

I am working on a filesystem project that needs to read/write files/folders from an specific path in the local disk. The problem is that I can't get it to work with Excel files (more generally speaking, any software that uses "indirect save" like TextEdit also; when I say "indirect save" I mean the process of creating and writing a new file, and finally removing the old file and renaming the new file to old file's name).

Every time that I try to open or save the file I get a "can't find/save the file" message, but there's no error message on the debug logs. 

My projects can be found at: https://github.com/elgutierrez/mirrorfs and I am running it on OSX 10.9 using OSXFUSE 2.8.2

**Comment by tv42** [comment]
Sounds like you didn't implement some operation that the program wants to use (or mis-implemented the semantics of one). Use the debug log to see what the client does. I do not have time to debug your filesystem for you.
