### ISSUE TITLE
Properly creating, opening, and using a socket. 

### ISSUE THREAD

**Issue by thrisp** [bazil/fuse#131]
Are there any example anywhere using unix domain sockets inside a mounted filesystem? I am getting completely stopped trying to create or manage a socket and something previously done to study would be helpful. 

I do not have actual code that is erroring just something I'm working with:

https://github.com/wSCP/site62/blob/develop/node/block.go#L28

I want to use that file as a socket or named pipe or fifo or channel.....I just do not know exactly what to do yet.

**Comment by tv42** [comment]
I'm not aware of any example. Non-regular files (fifos, sockets, ...) have no special functionality in FUSE. When you `bind(2)` a unix domain socket to a path that happens to be on a FUSE filesystem, you should just see a [`CreateRequest`](https://godoc.org/bazil.org/fuse#CreateRequest) with an [`os.FileMode`](https://golang.org/pkg/os/#FileMode) that has the `ModeSocket` bit set. FUSE has nothing to do with the `listen(2)` / `connect(2)` life of sockets.

I think your problem might be that you're trying to precreate the socket file. Just as outside of FUSE, the listener can't `bind(2)` if the socket already exists.

**Comment by thrisp** [comment]
My original attempt was looking for the create request, but I could not get that, in retrospect perhaps a permissions issue that I overlooked and may need to revisit. 

Precreating was a second attempt. 

A lot of this is new territory, and I will need to move around and examine things until I understand. 

Do I need to return any sort of handle from the create request for a socket? The creation process is still a mystery I need to work on.
