### ISSUE TITLE
Lookup not being called, instead always ENOENT

### ISSUE THREAD

**Issue by edrex** [bazil/fuse#132]
I'm updating camlistore.org to the latest bazil.org/fuse, from 9802bb510ca4cd1c18ffc840cf6fe9ef5d1546a8. I've fixed most of the breakages due to API changes, but `Lookup` isn't being called on the root node, and I'm not sure why.

https://github.com/edrex/camlistore/blob/update_fuse2/pkg/fs/root.go#L92

Whatever is being called instead always returns ENOENT

Any idea what might be going wrong?

**Comment by edrex** [comment]
figured it out, by adding 
```
var _ fs.NodeStringLookuper = (*root)(nil)
```

argument order wrong.

**Comment by tv42** [comment]
Yup. Was just typing that ;) The implements assertions really help my coding.

**Comment by edrex** [comment]
So, where are the default implementations for Lookup etc?

**Comment by tv42** [comment]
There's no default implementation as such. Different requests have different behavior that occurs if the target fs/node/handle does not implement the relevant handler. For `LookupRequest`, see the `ENOENT` in https://github.com/bazil/fuse/blob/37bfa8be929171feec943f3496bc4befdeaf10db/fs/serve.go#L1035

**Comment by edrex** [comment]
Thanks for the support! Just FYI, https://camlistore-review.googlesource.com/#/c/6196/
