### ISSUE TITLE
Doc: is overwriting *a in Attr implementation safe?

### ISSUE THREAD

**Issue by edrex** [bazil/fuse#133]
In [this CL](https://camlistore-review.googlesource.com/#/c/6196/3/pkg/fs/at.go,sidebyside@44), I've been flip-flopping between modifying `*a fuse.Attr` in place and overwriting the pointer with a new instance. https://godoc.org/bazil.org/fuse/fs#Node doesn't say whether the second approach is ok, but clockfs [modifies](https://github.com/bazil/fuse/blob/master/examples/clockfs/clockfs.go#L102). Does it matter?

**Comment by tv42** [comment]
Semantically, there's no difference between `*a = ...` and overwriting all of the fields one by one.

I would recommend you don't overwrite all of the fields; some of the fields you don't seem to care about are initialized to sane values for you, and you're currently overwriting those values with zeroes. For example, `Nlink` really should be 1 there, and setting `Valid` zero is probably not a good idea.

**Comment by edrex** [comment]
Thanks! I'll change to updating the values in place.

**Comment by tv42** [comment]
Let's keep this open until the docs are better.
