### ISSUE TITLE
Support OSXFUSE fssubtype

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#140]
https://github.com/osxfuse/osxfuse/wiki/Mount-options#fssubtype

The Linux `subtype` option takes an arbitrary identifying string, the OSXFUSE option takes an integer referring to one of the built-in definitions (see `/Library/Filesystems/osxfuse.fs/Contents/Info.plist`). I'm not sure it makes sense to try to unify them.

**Comment by tv42** [comment]
@presotto Would a separate `func OSXFSSubType(i uint32) MountOption` make sense to you? I'd happily take a pull request for that ;)

(Evidence that osxfuse treats it as uint32: `common/fuse_mount.h:36:    uint32_t fssubtype;                  // file system sub type id`)

**Comment by tv42** [comment]
I would also very much welcome somebody doing research on OSXFUSE/OS X and figuring out whether the `FSPersonalities` really *need* to be read from that plist file, or whether that's just a MacFUSE legacy with no reason for OSXFUSE to not support Linux-style `subtype=STRING`.

I find Ben, the OSXFUSE upstream, very amenable to changes once you can justify them sufficiently; a lot of the places where OSXFUSE deviates from Linux FUSE are from before his era, and he's cleaned up plenty of instances already.

**Comment by tv42** [comment]
One thing that comes to mind is that the linux convention is heavily in the style of `ext4`, `xfs`, `btrfs` and friends: lowercase single word. The OS X convention seems to be "user-friendly phrase":

```
                <key>Beagle</key>
                <dict>
                        <key>FSName</key>
                        <string>Beagle File System (OSXFUSE)</string>
                        <key>FSSubType</key>
                        <integer>9</integer>
                </dict>
```

So even if the number dance would not be needed, perhaps this would need to be `SubtypeName` or some other wording, where at some point Linux and such could *also* make use of a friendlier string somewhere.

Also, what's the distinction between `Beagle` / `Beagle File System (OSXFUSE)` there. Are both visible? That sounds like the string replacement for `9` would be two mount options.

**Comment by presotto** [comment]
I agree.  Forget my change for now.  If I need it, I'll give you back a
change with a SubTypeName or some such.  Mostly I was trying to make the
option match the usage message from the osxfuse mount helper, i.e., I was
being anal.

And next time I won't use the github desktop tool to do a push until I
understand it better.  First time I tried it and I didn't expect the paths
to get changed.

**Comment by tv42** [comment]
Heads up: the future of macOS support is in danger. If you care about FUSE on macOS, please encourage talented developers to pick up maintenance of the open source project. See https://github.com/bazil/fuse/issues/224

**Comment by tv42** [comment]
macOS support has been removed. If somebody wants to pick up maintaining an open source macOS FUSE, or wants to fund supporting the proprietary continuation of OSXFUSE, please get in touch.
https://github.com/bazil/fuse/issues/224
