### ISSUE TITLE
support for direct_io fusermount option

### ISSUE THREAD

**Issue by kortschak** [bazil/fuse#156]
It's unclear whether this exists, but it appears not. I am having some problems that I think will be cleared up by using "direct_io", but there is no way to pass that option to Mount. When I add a DirectIO mount option this fails with an invalid argument error, presumably because (I find out) that fusermount apparently does not handle this.

How do I go about specifying direct IO?

**Comment by omani** [comment]
When I want direct_io I uncomment below:
```
func (f *File) Open(ctx context.Context, req *fuse.OpenRequest, resp *fuse.OpenResponse) (fs.Handle, error) {
	// resp.Flags |= fuse.OpenDirectIO
	return f, nil
}
```

**Comment by vgough** [comment]
How are you mounting encfs, something like this `./encfs -f -o direct_io /tmp/crypt-raw /tmp/crypt` ?

**Comment by tv42** [comment]
Yes, the C FUSE libraries muddles up what's a mount option and what's just behavior of the FS, and has these kludges where mount options make the C library stealthily change the kernel<->fs communication. We're not gonna have any of that silliness.

You can disable the kernel page cache case by case with the `fuse.OpenDirectIO` flag in `fuse.OpenResponse`, like @omani showed.
