### ISSUE TITLE
Slow socket-file read (30seconds delay) when getting requests in "syscall.Read"

### ISSUE THREAD

**Issue by junjieqian** [bazil/fuse#157]
Hi, we have a performance problem when getting requests from channel, that it sometimes takes about 30seconds to read. It is running on Ubuntu with Go1.7.1.

According to the profiling results, the delay happens in `n, err := syscall.Read(c.fd(), m.buf)` (fuse.go:552). The lock and unlock operations finishes in nanoseconds or less.

Any suggestions on improving this issue? Or is there any special settings we missed?

**Comment by tv42** [comment]
That just means the FUSE kernel module isn't sending you more operations, at that time. Maybe you have too many outstanding requests that you're not completing? There's not enough information here to say much.

**Comment by junjieqian** [comment]
Thank you very much for your attention! I do have some more strace logs regarding this issue. It seems that you are correct, some other goroutine tries to `select` or use the handler and so causes long reading time.

My question is, is there any other goroutine trying to get the connection file handler `c.fd()`? This happens more frequent when I remove goroutines in [serve.go:L423
](https://github.com/bazil/fuse/blob/master/fs/serve.go#L423). **Or**, is there a way, I can limit the number of requests (though I do not think this is the case, as I have 16-core machine and the long delay happens even writing a 4KB file, which in my observation only has very few requests).

Following is the strace logs of normal `syscall.Read` and long wait. The only difference, I can tell, is as said that a lot of more `select` from another goroutine.
For each line, first element is PID, second one is how much time spent on this instruction, third one is handler to the process, forth one is the operations.

Long wait one:


> **13151**      0.000005 [00000000004f23c4] read(8,  <unfinished ...>
> 13153      0.000008 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 3} <unfinished ...>
> 13149      0.000010 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
> 13153      0.000061 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000064>
> 13153      0.000012 [000000000046c023] futex(0xc42007a910, FUTEX_WAKE, 1) = 1 <0.000010>
> 13158      0.000020 [000000000046c023] <... futex resumed> ) = 0 <0.031368>
> 13149      0.000008 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000095>
> 13158      0.000013 [000000000046c023] futex(0xc42007a910, FUTEX_WAIT, 0, NULL <unfinished ...>
> 13153      0.000006 [00000000004f23c4] write(8, "\20\0\0\0\332\377\377\377\n\0\0\0\0\0\0\0", 16 <unfinished ...>
> 13149      0.000008 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
> 13153      0.000020 [00000000004f23c4] <... write resumed> ) = 16 <0.000022>
> 13153      0.000028 [000000000046c023] futex(0xc4200e0110, FUTEX_WAIT, 0, NULL <unfinished ...>
> 13149      0.000054 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000085>
> 13149      0.000013 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout) <0.000084>
> 13149      0.000100 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout) <0.000083>
> 13149      0.000098 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout) <0.000083>
> 13149      0.000099 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout) <0.000083>
> ...... A lot more same record happens here.
> 13149      0.000721 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 1280}) = 0 (Timeout) <0.001344>
> 13149      0.000098 [000000000046c023] futex(0x745b78, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
> **13151**     30.186205 [00000000004f23c4] <... read resumed> "P\0\2\0\20\0\0\0\v\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 131152 <30.201482>

The normal one should be like

> **13151**      0.000020 [00000000004f23c4] read(8,  <unfinished ...>
> 13496      0.000023 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 3} <unfinished ...>
> 13149      0.000020 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000104>
> 13149      0.000026 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
> 13496      0.000044 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000077>
> 13496      0.000022 [000000000046c023] futex(0xc4204ae110, FUTEX_WAKE, 1) = 1 <0.000018>
> 13495      0.000047 [000000000046c023] <... futex resumed> ) = 0 <0.021090>
> 13149      0.000012 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000117>
> 13495      0.000063 [000000000046c023] futex(0xc4204ae110, FUTEX_WAIT, 0, NULL <unfinished ...>
> 13496      0.000033 [00000000004f23c4] write(2, "2016/10/21 17:31:35 [/0-0] flush"..., 55 <unfinished ...>
> 13149      0.000023 [000000000046bc07] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
> 13496      0.000039 [00000000004f23c4] <... write resumed> ) = 55 <0.000044>
> 13496      0.000030 [00000000004f23c4] write(8, "\20\0\0\0\0\0\0\0a\0\0\0\0\0\0\0", 16) = 16 <0.000023>
> 13149      0.000042 [000000000046bc07] <... select resumed> ) = 0 (Timeout) <0.000100>
> 13496      0.000022 [000000000046c023] futex(0xc4204b8110, FUTEX_WAIT, 0, NULL <unfinished ...>
> **13151**      0.000016 [00000000004f23c4] <... read resumed> "@\0\0\0\22\0\0\0b\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64 <0.000456>

**Comment by tv42** [comment]
Can't do anything here. It would help if you shared a small reproducible example -- right now, best bet is your filesystem logic is buggy.
