### ISSUE TITLE
Bugs when using chown or chmod to change attributes

### ISSUE THREAD

**Issue by junjieqian** [bazil/fuse#158]
It seems there is a bug in SetattrRequest passing values from `in`, as https://github.com/bazil/fuse/blob/master/fuse.go#L647.

That if running `chmod`, the `Uid` and `Gid` would be set to 0, which is default value of INT32. If running `chown`, the `Mode` would be set to another random number (on my platform, it is 67108864).

Did I miss something here? Or, if it is a bug, how can I fix it?
Thanks

**Comment by tv42** [comment]
Only the attributes that change are transmitted, the rest are not supposed to change. `Valid` tells you what fields are valid.

https://godoc.org/bazil.org/fuse#SetattrRequest
https://godoc.org/bazil.org/fuse#SetattrValid

**Comment by junjieqian** [comment]
Thank you very much for your explanation and point to the doc! I tried these, but the Valid field in SetattrRequest is not correct. For example, when using `chmod`, `Valid` is 1025 (`fuse.SetattrMode` is 1); when using `chown`, `valid` is 1030 (`fuse.SetattrUid` is 2).

These numbers are printed in `fuse.go`, right after passing from `in` to `setattrrequest`.

**Comment by tv42** [comment]
`1024` = `1024 | 1` = `1024 | fuse.SetattrMode`, so you know `req.Mode` is valid, makes sense for `chmod`.

`1030` = `1024 | 4 | 2` = `1024 | fuse.SetattrGid | fuse.SetattrUid`, makes sense for `chown`.

They're bit flags. For convenience, use like this:

```go
if req.Valid.Uid() {
    // change owner here
}
```

I don't know what `1024` means, but that'll be sorted later.

**Comment by junjieqian** [comment]
This really helps! Thanks a lot
