### ISSUE TITLE
Implementing traversable but not readable directories?

### ISSUE THREAD

**Issue by wrouesnel** [bazil/fuse#163]
I'm playing around with trying to implement an FS-backend for Hashicorp Vault (github.com/wrouesnel/vaultfs) based off another defunct project.

Everything works well provided that Vault policy allows you to get a listing from every component node in the path (when working with the `bazil.org/fuse/fs` interfaces).

But when you can't list an intermediate node (i.e. you can only send an empty result back to `ReadDirAll`), no subsequent `Lookup` is ever done on a node when trying to access a non-existent path. This makes it impossible to implement traversable but not readable directories, as far as I can tell (I suspect with the low-level API this would be possible, but everything _almost_ works with the high level API).

Am I missing something (or would a PR be accepted implementing the option?) to force `Lookup` to always occur when searching for a node from the `bazil.org/fuse/fs` interface so such behavior could be made available?

**Comment by tv42** [comment]
That sounds weird. I would have expected lookups regardless of any readdir.

As far as I understand what you're talking about, there is no PR to be made here; the kernel is in control of the behavior, not us.

Could you make a minimal (non-Vault-related) reproducing example? That'd save time on my end, eliminate misunderstandings, and push a bit more rubber ducky debugging on you ;)

**Comment by wrouesnel** [comment]
Turns out I had a check in one of my nodes which was returning failure (and the error term didn't yield a log line). So not a fuse problem at all - resolved completely on my end (after staring at it for a bunch of hours because of course).
