### ISSUE TITLE
use errors.As to get fuse.ErrorNumber from errors

### ISSUE THREAD

**Issue by akalin-keybase** [bazil/fuse#165]
I'd like to use https://github.com/pkg/errors in libkbfs and other places, which lets me wrap errors with stacktraces. However, this hides any implementation of fuse.ErrorNumber that a particular error might implement.

It's possible to fix this on the libfuse side by wrapping every error, but that's error-prone.

Looks like there's only one place in bazil that checks for ErrorNumber: https://github.com/bazil/fuse/blob/master/fs/serve.go#L831

What do you think of doing

```
if ferr, ok := errors.Cause(err).(fuse.ErrorNumber); ok {
```

instead?

This will pull in a dependency on pkg/error from bazil, but it seems like the error-wrapping package that's "closest" to core.

**Comment by akalin-keybase** [comment]
Another integration with pkg/errors would be to print out errors with "%+v" to also print out stack traces, but that might bloat up the logs, so I'm not 100% sure about it.

**Comment by akalin-keybase** [comment]
Actually, this pulls in another old issue, which is the fact that one needs to depend on bazil.org/fuse in order to work with `fuse.Errno`.

What do you think of adding a way to pass in a `func(error) fuse.Errno` to bazil instead?

**Comment by tv42** [comment]
This might happen through errors.As

**Comment by tv42** [comment]
errors.As is now used in 3bebd277fa844a81aaabccac0c6ee81b5e59205b.

If you have a real need for not depending on fuse to implement ErrorNumber, please share more about the use case -- I don't see fuse logic depending on fuse as an issue, and mapping errors to the correct kernel error is very much FUSE logic, in my mind. As in, there are plenty of special values that mean things, you can't just return something.
