### ISSUE TITLE
Readdirall is missing path parameter

### ISSUE THREAD

**Issue by omani** [bazil/fuse#167]
I am trying to readdirall in a specific path. I saw other implementations of libfuse using readdir(..., path..) with a `path` parameter so I know in which path I am.

How am I suppose to know which path (directory) I am right now when looking up entries in that directory?

**Comment by tv42** [comment]
Unix filesystems operate on nodes and file handles, not path names. A node gets returned from create/lookup calls, and from there on that's the node, no matter what all paths it happens to be reachable through at any moment. The `ReadDirAll` method is called on the `Node` that is the directory being read.

`libfuse` the C library has a confusing and broken mode that builds a path-based illusion on top of that reality. I wouldn't recommend writing filesystems using it.

I'd suggest reading https://github.com/bazil/zipfs and https://github.com/bazil/bolt-mount

**Comment by omani** [comment]
thank you for clarification.
