### ISSUE TITLE
Writebackcache issues

### ISSUE THREAD

**Issue by omani** [bazil/fuse#168]
Hi,

everytime I enable `fuse.WritebackCache()` I do get problems with the files I create/copy.

for example when copying mp3s to my fuse filesystem. the mp3s start to skip at random points.
but it is 100% working when not using the writebackcache.

is this a known issue? how can I avoid this?

**Comment by omani** [comment]
my `Write()` looks like this:

```go
logrus.Debugf("Writing %s to tempfile: %s", f.name, f.tempfile)
	file, err := os.OpenFile(f.tempfile, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)

	if err != nil {
		logrus.Errorf("An error occurred while opening temporary file for writing: %s", err.Error())
		return fuse.EIO
	}

	defer file.Close()

	size, err := file.WriteAt(req.Data, req.Offset)

	if err != nil {
		logrus.Errorf("An error occurred while appending data to temporary file: %s", err.Error())
		return fuse.EIO
	}

	resp.Size = size
```

**Comment by omani** [comment]
my guess is that the writes happen too quick or maybe random (async?). but I could be wrong.

however, I see different log outputs in my console when enabling writebackcache. the log outputs are more unordered (like not sequential) but like I said, I could be wrong.

**Comment by tv42** [comment]
> my `Write()` looks like this:
> 
> ```go
> logrus.Debugf("Writing %s to tempfile: %s", f.name, f.tempfile)
> 	file, err := os.OpenFile(f.tempfile, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
...
> 	defer file.Close()

Check your errors.

> 	size, err := file.WriteAt(req.Data, req.Offset)

The combination of O_APPEND and WriteAt is pointless, and on Linux O_APPEND takes priority over the offset you ask to write at. It's likely you're corrupting your file content, there.

**Comment by omani** [comment]
ah nice. that was it. what a pity I didn't think about O_APPEND. now it works.

thank your very much!
