### ISSUE TITLE
Help wanted?

### ISSUE THREAD

**Issue by fd0** [bazil/fuse#174]
Hi @tv42,

it seems that this project doesn't get much attention lately, may I ask how we can help you? I'd be willing to spend time on the issues, maybe triage them.

**Comment by themihai** [comment]
@fd0 I believe this project is dead. It would definitely help if someone would take ownership and maintain it. Fixing the deadlock issues would be great!

**Comment by fd0** [comment]
So, hm. I'd like to contribute, too. And it seems people from Twitter have also forked this repo, ping @jasonbs10

The question now is: Is this worth a fork? There's also the (actively maintained) https://github.com/hanwen/go-fuse

**Comment by tv42** [comment]
I am not, at this time, aware of a minimal way of "just fixing" the deadlock triggered by the recent Go runtime changes. Plan A is to implement polling FUSE and see if that helps; plan B is to suck it up and never consume a filesystem from the process serving it. (That's a large amount of churn for the codebase.)

As far as I can read the kernel source, the change in hanwen/go-fuse merely decreases the duration of the race window; the aim of bazil.org/fuse is to be 100% race free.

**Comment by jasonbs10** [comment]
@fd0 I felt like this codebase was easy to work with, and Tv is responsive, however due to shifting priorities we are no longer updating our fork.

**Comment by fd0** [comment]
@tv42 what about smaller things like updating this library to use the internal `context` package? I've created a PR in #200, does that help you? Is there anything else we can do?

**Comment by tv42** [comment]
@fd0 That's a great example of something where the work of making the change is actually less than the work of confirming someone else did it right -- it's a completely mechanical transformation.

**Comment by anderspitman** [comment]
@fd0 what's your current read on the state of this library? I know you're using it for restic. Have you had major issues?

I've been experimenting with it, and it's great to work with, but the project I'm working on will have to be production quality when it's done. I can't afford known deadlock problems, which I wasn't aware was a thing until reading this just now.

**Comment by tv42** [comment]
@anderspitman The only deadlock I am aware of is when the fuse server and the filesystem client are in the same Go process. Normal use of the filesystem should never trigger any deadlocks. I'm still unsure on which route will be easier; to completely avoid doing that for testing, or to try to figure out why the Go runtime does what it does and how to work around it.

**Comment by anderspitman** [comment]
@tv42 oh so that could only happen for example if I were to try to read or write a file from go from the same process that is running the fuse server? I shouldn't need to do that. Which would be a relief because this is an excellent library.

**Comment by tv42** [comment]
Yes, a Go process serving a fuse mount it is using itself is the only known deadlock.

**Comment by tv42** [comment]
The deadlock was "solved" by avoiding it -- tests put filesystem client in a subprocess, starting from 3f5ad9058d81bedd9d0181e676373e6b8053bb2a.

I don't think there's anything actionable here. Good quality contributions are very much welcome.

**Comment by tv42** [comment]
Flagging as invalid because this is not a bug report, enhancement, and not really a question either as I use that as criteria for improving docs. No offense intended!

**Comment by fd0** [comment]
No offense taken! I'm thankful you have the time and energy to work on this library again. Thank you very much for your work!
