### ISSUE TITLE
How to read from named pipe files (os.ModeNamedPipe)?

### ISSUE THREAD

**Issue by lateefj** [bazil/fuse#177]
I would like to mount a message queue as a named pipe file. I have tried to implement the fs.NodeOpener interface which works great however fs.HandleReader interface doesn't seem to ever get called. Wondering if there are any suggestions on how to implement something like this?

**Comment by tv42** [comment]
Named pipes are named pipes, even on a FUSE filesystem. Maybe you just want a pseudofile (dynamically generated contents), like `/proc` entries are?

**Comment by lateefj** [comment]
Great point @tv42. I guess I was approaching it as I have a channel that I am reading from which the closes file type was a pipe. However I think a pseudofile approach would be better. Any examples for how to do this? File attributes, mode type ect?

**Comment by lateefj** [comment]
@tv42 I think I got enough from this post: https://github.com/bazil/fuse/issues/111. Tail seems to be skipping every other message but I am guessing that is a bug on my end. 
Thanks so much for your help!

**Comment by tv42** [comment]
Happy you got it going!
