### ISSUE TITLE
InvalidateNode block process question

### ISSUE THREAD

**Issue by slhad** [bazil/fuse#180]
Hello, just a question to understand what I am doing wrong.

When a small file (size<1ko) is accessed by 2 process, one in read and another one in write,
The file is read then written(+flush) then reread, the second read does not make a call to
- Read(ctx context.Context, req *fuse.ReadRequest, resp *fuse.ReadResponse) error
The data is returned from the kernel.

(No close/released of the file between each calls)

So I try to invalidate the node at the end of Write(...) but my program hang at the instruction InvalidateNode, I have debugged as deep as
```
func (c *Conn) writeToKernel(msg []byte) error {
/*...*/
    nn, err := syscall.Write(c.fd(), msg)
/*...*/
}
```
from /fuse.go but did not understand what was happening

Did I miss something when using it ?

```
func (f *File) Write(ctx context.Context, req *fuse.WriteRequest, resp *fuse.WriteResponse) error {

/*
Handling write
*/

    err := req.Conn.InvalidateNode(req.Node,0,-1)
    if err != nil {
        log.warning("Not cached")
    }
}
```

**Comment by tv42** [comment]
You're not responding to the kernel so it could release its lock on the file, while you're telling the kernel to do operations on the file -- you've caused a deadlock. Invalidations are meant for network filesystems that e.g. lose a lease based on an incoming network message or timeout.

Why are you trying to prevent the pagecache from working normally? Perhaps you want to disable it fully, then?

**Comment by tv42** [comment]
Sees like this is getting no response. Flagging as doc to use as input for better docs on invalidation, one day, maybe. (I hate documenting things I did not make the rules for; it's just Linux.)
