### ISSUE TITLE
Is it possible to set custom icons?

### ISSUE THREAD

**Issue by podviaznikov** [bazil/fuse#182]
Is it possible to set custom icons for files and dirs?
I'm new to FUSE and bazil and not sure yet where to find that information.

**Comment by tv42** [comment]
It should be easy to add (OSX-only) support for https://github.com/osxfuse/osxfuse/wiki/Mount-options#volicon -- but that doesn't exist right now, and I worry about how one would test that.

**Comment by tv42** [comment]
Oh oh, from that link, and the reason why I haven't added that feature: I think you can get that effect just by including some files in the top directory: `/.VolumeIcon.icns` is one of them. I'm no expert on OS X or Finder..

**Comment by tv42** [comment]
Heads up: the future of macOS support is in danger. If you care about FUSE on macOS, please encourage talented developers to pick up maintenance of the open source project. See https://github.com/bazil/fuse/issues/224

**Comment by tv42** [comment]
macOS support has been removed. If somebody wants to pick up maintaining an open source macOS FUSE, or wants to fund supporting the proprietary continuation of OSXFUSE, please get in touch.
https://github.com/bazil/fuse/issues/224
