### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [bazil/fuse#184]
For [restic](https://github.com/restic/restic), we'll switch to `dep` shortly, and it would be very helpful if you could tag a release. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by tv42** [comment]
Consider what exists now as 0.0.0. There will still need to be radical API changes.

**Comment by nhooyr** [comment]
@tv42 Was thinking of using this. What are the big issues with this library that require radical API changes?

**Comment by tv42** [comment]
@nhooyr The fuse.ReadRequest API means handing chunks of memory out without visibility into their lifetime, and that causes too much GC churn, especially on macOS. That API will likely be replaced by a more net/http-style "we'll call your handler" API.

There's also a ton of inconsistency in naming, inherited from years back, and fixing that will be a lot of little API breakages.

**Comment by tv42** [comment]
`go mod` is very happy to use just git commits. Whether a v0.0.1 tag exists or not shouldn't make much of a difference to your workflow.
