### ISSUE TITLE
Unable to rename files by sftp

### ISSUE THREAD

**Issue by ErAzOr2k** [bazil/fuse#185]
Hi,

I'm trying to develop something similar to mirrorfs [https://github.com/elgutierrez/mirrorfs](url), which basically respresents a already existing file structure on my local hard drive.

The relevant code parts are:
```
func (d *Dir) Lookup(ctx context.Context, name string) (fs.Node, error) {
	d.RLock()
	defer d.RUnlock()
	path := filepath.Join(d.path, name)
	stats, err := os.Stat(path)
	if err != nil {
		return nil, fuse.ENOENT
	}	

	switch {
		case stats.IsDir():
			return d.fs.newDir(path, stats.Mode()), nil
		case stats.Mode().IsRegular():
			return d.fs.newFile(path, stats.Mode()), nil
		default:
			panic("Unknown type in filesystem")
	}
}
```
and:
```
func (d *Dir) Rename(ctx context.Context, req *fuse.RenameRequest, newDir fs.Node) error {
	nd := newDir.(*Dir)
	log.Println(req)
	if d.attr.Inode == nd.attr.Inode {
		d.Lock()
		defer d.Unlock()
	} else if d.attr.Inode < nd.attr.Inode {
		d.Lock()
		defer d.Unlock()
		nd.Lock()
		defer nd.Unlock()
	} else {
		nd.Lock()
		defer nd.Unlock()
		d.Lock()
		defer d.Unlock()
	}

	if exists := d.exists(req.OldName); !exists {
		log.Println("Rename ERR: ENOENT")
		return fuse.ENOENT
	}

	oldPath := filepath.Join(d.path, req.OldName)
	newPath := filepath.Join(nd.path, req.NewName)

	if err := os.Rename(oldPath, newPath); err != nil{
		log.Println("Rename ERR: ", err)
		return err
	}
	return nil
}
```

Renaming files within terminal works without a problem:
`<- Getattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=1426] 0x0 fl=0-> [ID=0x2] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Access [ID=0x3 Node=0x1 Uid=0 Gid=0 Pid=1426] mask=0x1-> [ID=0x3] Access<- Getattr [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0x4] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Open [ID=0x5 Node=0x1 Uid=0 Gid=0 Pid=1425] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0x5] Open 0x1 fl=0<- Read [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock2017/07/31 16:23:00 ReadDirAll  /mnt/source/
2017/07/31 16:23:00 ReadDirAll file {0 file testfile}
-> [ID=0x6] Read 32<- Lookup [ID=0x7 Node=0x1 Uid=0 Gid=0 Pid=1425] "testfile"-> [ID=0x7] Lookup 0x2 gen=0 valid=1m0s attr={valid=0s ino=2 size=0 mode=-rw-r--r--}<- Getattr [ID=0x8 Node=0x2 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0x8] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Read [ID=0x9 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0x9] Read 0<- Read [ID=0xa Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0xa] Read 0<- Release [ID=0xb Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0-> [ID=0xb] Release<- Lookup [ID=0xc Node=0x1 Uid=0 Gid=0 Pid=4225] "testfile2"-> [ID=0xc] Lookup error=ENOENT<- Getattr [ID=0xd Node=0x2 Uid=0 Gid=0 Pid=4225] 0x0 fl=0-> [ID=0xd] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Lookup [ID=0xe Node=0x1 Uid=0 Gid=0 Pid=4225] "testfile2"-> [ID=0xe] Lookup error=ENOENT<- Lookup [ID=0xf Node=0x1 Uid=0 Gid=0 Pid=4225] "testfile2"-> [ID=0xf] Lookup error=ENOENT<- Rename [ID=0x10 Node=0x1 Uid=0 Gid=0 Pid=4225] from "testfile" to dirnode 0x1 "testfile2"2017/07/31 16:23:07 Rename [ID=0x10 Node=0x1 Uid=0 Gid=0 Pid=4225] from "testfile" to dirnode 0x1 "testfile2"
-> [ID=0x10] Rename`

But renaming a file by sftp fails with error message (from sftp client) something similar to "no such file found":
`<- Getattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0x2] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Getattr [ID=0x3 Node=0x1 Uid=0 Gid=0 Pid=1426] 0x0 fl=0-> [ID=0x3] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Access [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=1426] mask=0x1-> [ID=0x4] Access<- Getattr [ID=0x5 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0x5] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Open [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=1425] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0x6] Open 0x1 fl=0<- Read [ID=0x7 Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock2017/07/31 16:21:56 ReadDirAll  /mnt/source/
2017/07/31 16:21:56 ReadDirAll file {0 file testfile}
-> [ID=0x7] Read 32<- Lookup [ID=0x8 Node=0x1 Uid=0 Gid=0 Pid=1425] "testfile"-> [ID=0x8] Lookup 0x2 gen=0 valid=1m0s attr={valid=0s ino=2 size=0 mode=-rw-r--r--}<- Getattr [ID=0x9 Node=0x2 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0x9] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Read [ID=0xa Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0xa] Read 0<- Read [ID=0xb Node=0x1 Uid=0 Gid=0 Pid=1425] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0xb] Read 0<- Release [ID=0xc Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0-> [ID=0xc] Release<- Getattr [ID=0xd Node=0x2 Uid=0 Gid=0 Pid=1425] 0x0 fl=0-> [ID=0xd] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Lookup [ID=0xe Node=0x1 Uid=0 Gid=0 Pid=1425] "testfile2"-> [ID=0xe] Lookup error=ENOENT`

It seems, that rename don't get triggered by fuse.

I hope anyone can help me out with this issue.
Thanks

**Comment by tv42** [comment]
If you can fix the line breaks in those log snippets, that'd be great.

**Comment by tv42** [comment]
So, it seems sftp doesn't do a rename; it might be trying to do a create+copy+delete. However, your second log snippet shows only one mention of `testfile2`, which is a `Lookup` and not any kind of a create operation. Perhaps your `ReadDir` result already listed that file as existing?

**Comment by ErAzOr2k** [comment]
I can confirm that file testfile2 is not existing, so ReadDirAll is not listing this file.
I will provide a full log later today.

**Comment by ErAzOr2k** [comment]
This is the full log when trying to rename file "test1" to "rename1"

> sudo ./mirrorfs -debug -mirror /mnt/source/ -mount /mnt/target/

> <- Getattr [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0x2] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Open [ID=0x3 Node=0x1 Uid=1000 Gid=1000 Pid=4128] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0x3] Open 0x1 fl=0<- Getattr [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0x4] Getattr valid=0s ino=1 size=0 mode=drwxrwxrwx<- Read [ID=0x5 Node=0x1 Uid=1000 Gid=1000 Pid=4128] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock2017/08/01 18:08:28 ReadDirAll  /mnt/source/
> 2017/08/01 18:08:28 ReadDirAll file {0 file test1}
> 2017/08/01 18:08:28 ReadDirAll file {0 file test2}
> 2017/08/01 18:08:28 ReadDirAll file {0 file test3}
> -> [ID=0x5] Read 96<- Lookup [ID=0x6 Node=0x1 Uid=1000 Gid=1000 Pid=4128] "test1"-> [ID=0x6] Lookup 0x2 gen=0 valid=1m0s attr={valid=0s ino=2 size=0 mode=-rw-r--r--}<- Getattr [ID=0x7 Node=0x2 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0x7] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Lookup [ID=0x8 Node=0x1 Uid=1000 Gid=1000 Pid=4128] "test2"-> [ID=0x8] Lookup 0x3 gen=0 valid=1m0s attr={valid=0s ino=3 size=0 mode=-rw-r--r--}<- Getattr [ID=0x9 Node=0x3 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0x9] Getattr valid=0s ino=3 size=0 mode=-rw-r--r--<- Lookup [ID=0xa Node=0x1 Uid=1000 Gid=1000 Pid=4128] "test3"-> [ID=0xa] Lookup 0x4 gen=0 valid=1m0s attr={valid=0s ino=4 size=0 mode=-rw-r--r--}<- Getattr [ID=0xb Node=0x4 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0xb] Getattr valid=0s ino=4 size=0 mode=-rw-r--r--<- Read [ID=0xc Node=0x1 Uid=1000 Gid=1000 Pid=4128] 0x1 4096 @0x60 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0xc] Read 0<- Read [ID=0xd Node=0x1 Uid=1000 Gid=1000 Pid=4128] 0x1 4096 @0x60 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock-> [ID=0xd] Read 0<- Release [ID=0xe Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0-> [ID=0xe] Release<- Getattr [ID=0xf Node=0x2 Uid=1000 Gid=1000 Pid=4128] 0x0 fl=0-> [ID=0xf] Getattr valid=0s ino=2 size=0 mode=-rw-r--r--<- Lookup [ID=0x10 Node=0x1 Uid=1000 Gid=1000 Pid=4128] "rename1"-> [ID=0x10] Lookup error=ENOENT

**Comment by tv42** [comment]
Your log snippets are still pretty darn unreadable, can you fix the line breaks?

**Comment by tv42** [comment]
That second log snippet seems like it's cut off just before the interesting stuff happens. Lookup fails -> file doesn't exist -> the next request would likely be `Create` (in a create+copy+delete kind of a rename).

**Comment by ErAzOr2k** [comment]
Sorry, next logs will be better readable ;)
The log snippet is definitely not cut off. This is all I get.

So you have an idea, how I can provide more info?

**Comment by tv42** [comment]
Can't do anything here. If you want help, you need to ask a complete question. It would help if you had an example others can run.
