### ISSUE TITLE
Panic when using application in fstab as fuse

### ISSUE THREAD

**Issue by omani** [bazil/fuse#186]
Hi,

when using my application in fstab (as a fuse type) I get the following error:
```
panic: fusermount: exec: "fusermount": executable file not found in $PATH
```

fstab entry is:
```
myapp	/home/me/mountpoint	fuse	_netdev,users 0 0
```

```myapp``` is a bash script in /usr/bin containing the command invocation to my app.

this issue is due to the command invocation of mount being made as the root user (fstab mounts are done by root, even if the fstab entry has "users" in options):
```
mount /home/me/mountpoint
```

tracking this issue back in the code it seems that:
```
cmd := exec.Command(
		"fusermount",
		"-o", conf.getOptions(),
		"--",
		dir,
	)
	cmd.Env = append(os.Environ(), "_FUSE_COMMFD=3")

	cmd.ExtraFiles = []*os.File{writeFile}

	var wg sync.WaitGroup
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("setting up fusermount stderr: %v", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return nil, fmt.Errorf("setting up fusermount stderr: %v", err)
	}

	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("fusermount: %v", err)
	}
```
in mount_linux.go fails in the cmd.Start() section due to "fusermount" in the exec.Command() not being present in $PATH. doing some debugging with:
```
logrus.Info("PATH IS :", os.Getenv("PATH"))
```
above the ```exec.Command(...)``` line the PATH environment for the root user is empty.

so my solution is to set a default PATH environment variable right above that line:
```
os.Setenv("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
```

which solves the issue for me. but I am pretty sure that this is not the right place to do it (or even the right way to do it).

so just wanted to let you guys know.

**Comment by omani** [comment]
another solution I thought would be using:
```
os.LookPath("fusermount")
```
to get the path to fusermount (like "which fusermount" in bash). but it seems that for this command to work you also need at least something set in $PATH. in this case the dirname of ```/usr/bin/which```.

tricky.

**Comment by omani** [comment]
I guess since this ```mount()``` call is OS dependent (mount_freebsd.go, mount_linux.go, etc.) setting the $PATH env variable in the file mount_linux.go should be ok since the directories in PATH are very linux specific (see my setenv above). but I let you guys decide how to deal with this issue.

thanks.

**Comment by omani** [comment]
just found another solution to my issue:
set the PATH variable in the bash script in ```/usr/bin``` I mentioned above.

so I guess this isn't really an issue in the code. I just had to pass the PATH env var to my application.

**Comment by tv42** [comment]
Empty `PATH` is going to make just about everything fail, including typical shell scripts. I'm not sure why whatever is interpreting your `/etc/fstab` is doing that, but it really shouldn't. Happy you found a workaround, but I'd encourage you to explore your distro a little and see what invokes the mount (`mount -a`, systemd, etc) and see about reporting that.

**Comment by togetherbeer** [comment]
Hey, running into this with [togetherbeer/journalfs](https://github.com/togetherbeer/journalfs)

I asked in #debian-devel if it's normal that PATH should be unset when mount calls filesystem programs, and the answer came back yes: the environment is cleaned because the mount program runs with setuid -> root.

It looks like Debian, Ubuntu and Arch get mount from the [utils-linux](https://github.com/karelzak/util-linux) package, which [drops PATH and other vars from the environment on purpose](https://github.com/karelzak/util-linux/blob/7397f2c1f955569743c68c900ca873fd9e211833/sys-utils/mount.c#L664)

For bazil.org/fuse programs to be mountable via fstab or `mount -t` (without bundling a wrapper), it might be worth reconsidering this issue!
