### ISSUE TITLE
Unable to implement symlinks

### ISSUE THREAD

**Issue by nadgowdas** [bazil/fuse#187]
Hi,

I've created a filesystem to from this project. I am facing problem implementing a symlink functionality with this filesystem interface. And I would really appreciate any help regarding this.

**Comment by omani** [comment]
but what is the problem?

**Comment by nadgowdas** [comment]
@omani Sorry, I was not clear. I was actually looking for some sample implementation of symlink with bazil-fuse. I am now able to implement it. 

Closing this issue.
