### ISSUE TITLE
tail -f not working with invalidation

### ISSUE THREAD

**Issue by omani** [bazil/fuse#188]
hi,

I have this weird problem, that invalidating the node does not update the content of a file when it is being tailed by ```tail -f```. but it works for 
```
watch -n0.1 'cat mountpoint2/file'
```
instantly.

what I am trying:
* mount filesystem into mountpoint1
* mount the same filesystem into mountpoint2 (imitating another user/device, etc.)

updates (write calls to files) are pushed via websocket notifications to all devices (hey new updated content, go READ nodeID XY again). the appropriate listening node will call its ```InvalidateEntry``` on its files (their parent) along with ```InvalidateAttr()```.

As I've said everything seems to work. but not ```tail -f```. since file I/Os are commonly done by a full chain of calls (open, getattr, read bytes, release) by most applications, this is fine for me. but I am wondering why ```tail -f``` won't work here.

furthermore all operations are network calls. I am not using any caching mechanisms here. so each call should go to the backend.

should someone suggest opening nodes with OpenDIrectIO. I don't want to use direct_io since it has severe performance issues (too slow via network).

any hints?

**Comment by omani** [comment]
oh I think I know why. kernel cache invalidation does not work for already opened files, could this be?

**Comment by tv42** [comment]
`tail -f` uses mtime polling or inotify, depending on version. I don't think we have support for inotify in bazil.org/fuse yet, and you make no mention of updating the mtime either.

**Comment by omani** [comment]
I am updating mtime (on websocket notification). a ```Forget()``` call should enforce a new ```GetAttr()``` call, which also updates mtime.

**Comment by omani** [comment]
this issue has been resolved. thanks

**Comment by mostcute** [comment]
@omani 

any suggestion to solve this? thanks
