### ISSUE TITLE
Set custom return codes

### ISSUE THREAD

**Issue by omani** [bazil/fuse#189]
Hi,

how can I set custom return codes which I can see when invoking:
```
echo $?
```
in my mountpoint after - for example - writing to a file (and we assume I have set a custom error message/number in `Write()` there)?

I tried with implementing my own custom error interface:
```
type ErrorNumber interface {
    // Errno returns the the error number (errno) for this error.
    Errno() Errno
}
```

but with no luck.

**Comment by tv42** [comment]
$? is the exit code of the last command. That's up to the command do what it wants.

FUSE can only return errors to filesystem operations. Make your Write method return e.g. fuse.EPERM and you should see a write get the write(2) syscall return -1, errno=EPERM.

I see no bug here, so closing this report.

**Comment by omani** [comment]
alright, thanks.
