### ISSUE TITLE
Missing fuse.ENOTEMPTY

### ISSUE THREAD

**Issue by hookenz** [bazil/fuse#192]
When a directory is non-empty and you issue a Remove request the appropriate value to return is fuse.ENOTEMPTY.  However, that error code is missing from the luist.  Attempting to return the correct value fails as it will default back to EIO.  Please add ENOTEMPTY to the list of errors available in fuse.go

**Comment by tv42** [comment]
> Attempting to return the correct value fails as it will default back to EIO.

Can you expand on that?

The list of error codes in package fuse is not meant to be exhaustive, it's just the most common ones I got tired of typing out. You can convert any `syscall.Errno` to `fuse.Errno`.

**Comment by swt2c** [comment]
There's already PR #150 for this.  tv42 hasn't merged any PR's in a long time.  :(

**Comment by tv42** [comment]
All you ever needed to do was `fuse.Errno(syscall.ENOTEMPTY)`, but even that is unnecessary after 3bebd277fa844a81aaabccac0c6ee81b5e59205b.
