### ISSUE TITLE
Statfs is returning incorrect number of files used in df -i

### ISSUE THREAD

**Issue by ncw** [bazil/fuse#194]
An rclone user reported this to me...

I have [a Statfs call](https://github.com/ncw/rclone/blob/master/cmd/mount/fs.go#L51-L66) which l've patched to look like this.  Note the `resp.Files = 123` and the `resp.Ffree = 456`

```go
// Statfs is called to obtain file system metadata.
// It should write that data to resp.
func (f *FS) Statfs(ctx context.Context, req *fuse.StatfsRequest, resp *fuse.StatfsResponse) (err error) {
	defer log.Trace("", "")("stat=%+v, err=%v", resp, &err)
	const blockSize = 4096
	const fsBlocks = (1 << 50) / blockSize
	resp.Blocks = fsBlocks  // Total data blocks in file system.
	resp.Bfree = fsBlocks   // Free blocks in file system.
	resp.Bavail = fsBlocks  // Free blocks in file system if you're not root.
	resp.Files = 123        // Total files in file system.
	resp.Ffree = 456        // Free files in file system.
	resp.Bsize = blockSize  // Block size
	resp.Namelen = 255      // Maximum file name length?
	resp.Frsize = blockSize // Fragment size, smallest addressable data size in the file system.
	return nil
}
```

However mounting this fs on linux and doing `df -i` I see the `123` number repeated.

```
$ df -i ~/mnt/tmp/
Filesystem     Inodes IUsed IFree IUse% Mounted on
local:/tmp/big    123   123     0  100% /home/ncw/mnt/tmp
```

I looked through the bazil source and I didn't see anything wrong.  Though the `kstatfs` struct appears to be missing the `f_favail` that is in the [kernel statvfs struct](http://man7.org/linux/man-pages/man3/statvfs.3.html) though I don't know how this passed through the FUSE layer.

**Comment by ncw** [comment]
Any ideas on this?  Happy to send a PR but I couldn't figure out where the problem is!

Thanks

**Comment by tv42** [comment]
Looks like just sloppy programming with no test coverage, inherited all the way from the first commit. Should be better now.

**Comment by ncw** [comment]
@tv42 thanks for fixing that - I can confirm the fix works!
