### ISSUE TITLE
libfuse compatible interface?

### ISSUE THREAD

**Issue by mqliang** [bazil/fuse#197]
Is it possible to add a libfuse compatible layer? With such a interface, implement a custom filesystem will be much more convenient since user just need to implement a bunch of functions.

C libfuse interface is like:

```
struct fuse_operations_compat2 {
	int (*getattr)	   (const char *, struct stat *);
	int (*readlink)	   (const char *, char *, size_t);
	int (*getdir)	   (const char *, fuse_dirh_t, fuse_dirfil_t_compat);
	int (*mknod)	   (const char *, mode_t, dev_t);
	int (*mkdir)	   (const char *, mode_t);
	int (*unlink)	   (const char *);
	int (*rmdir)	   (const char *);
	int (*symlink)	   (const char *, const char *);
	int (*rename)	   (const char *, const char *);
	int (*link)	   (const char *, const char *);
	int (*chmod)	   (const char *, mode_t);
	int (*chown)	   (const char *, uid_t, gid_t);
	int (*truncate)	   (const char *, off_t);
	int (*utime)	   (const char *, struct utimbuf *);
	int (*open)	   (const char *, int);
	int (*read)	   (const char *, char *, size_t, off_t);
	int (*write)	   (const char *, const char *, size_t, off_t);
	int (*statfs)	   (const char *, struct statfs *);
	int (*flush)	   (const char *);
	int (*release)	   (const char *, int);
	int (*fsync)	   (const char *, int);
	int (*setxattr)	   (const char *, const char *, const char *,
			    size_t, int);
	int (*getxattr)	   (const char *, const char *, char *, size_t);
	int (*listxattr)   (const char *, char *, size_t);
	int (*removexattr) (const char *, const char *);
};

```

**Comment by tv42** [comment]
This Go library will never be compatible with a C library; that goes against the point of using Go.

I consider the path-based layer of libfuse fundamentally broken, and don't see how one could ever create a bug-free non-toy, non-readonly, filesystem using it.

The intent is to make bazil.org/fuse/fs an as-easy-as-possible framework for creating filesystems. It may not be there yet, and it surely is missing a lot of documentation -- but fundamentally, you have to understand Linux filesystems to begin with; the concepts of Node and Handle cannot be ignored without consequences.

Any kind of borrowing from the C libfuse is an explicit non-goal; I do not consider that library very good. This FUSE library is developed against what the Linux kernel does, not what some old C library did.

I don't see what can be done here; feel free to elaborate, and we can re-open the bug if something actionable comes out of it.

**Comment by mqliang** [comment]
@tv42 
> I consider the path-based layer of libfuse fundamentally broken, and don't see how one could ever create a bug-free, non-toy, non-readonly, filesystem using it.

I am not a fs expert. I am thinking how about adding a wrapper layer which encapsulate bazil/fuse details(Fs, Dir, File), and providing C libfuse like (path based) interface? Is it possible?
