### ISSUE TITLE
Rename example

### ISSUE THREAD

**Issue by themester** [bazil/fuse#201]
Hello,

I am getting problems to rename a file or directory and I wanna know if the are any Rename example.
You can see my code at [my gogs](https://gogs.mester.pw/themester/mfs/src/master/dir.go#L82)

Thanks.

**Comment by zhengxiaochuan-3** [comment]
https://github.com/tiglabs/containerfs/blob/661ebaeb27d706d00d875e9d1e19a3f0db57fea7/client/fuse/dir.go#L388
@themester 
my code

**Comment by themester** [comment]
@zhengxiaochuan-3 thanks. I [solved it](https://gogs.mester.pw/themester/mfs/src/master/dir.go#L85) finally but for new users it would be well to add more documentation or more examples as [goinsta](https://github.com/ahmdrz/goinsta/tree/master/examples) does

**Comment by zhengxiaochuan-3** [comment]
@themester  have you met this issue ? #202

**Comment by tv42** [comment]
Docs as a whole need a lot of work. Let's not keep issues about individual missing things until the general state is significantly better than current; what docs are missing is obvious from skimming the source.
