### ISSUE TITLE
how open writeback cache  on linux 3.10 kernel ?

### ISSUE THREAD

**Issue by ghost** [bazil/fuse#203]
how open writeback cache  on linux 3.10 kernel ?

when user write 20 byte ,the performace is very slow .

so open write back cache can improvce write performanche

**Comment by tv42** [comment]
I'm not sure what you mean by "open writeback cache".

The kernel page cache buffers writes and sends them to the FUSE userspace server as full pages, by default. You'd have to explicitly opt *out* of that behavior, with `OpenDirectIO`.

What are you doing, what are you observing, how does it differ from expected?

**Comment by tv42** [comment]
Can't do anything here.
