### ISSUE TITLE
fuseutil : HandleRead panics when the resp data is not big enough to hold the file

### ISSUE THREAD

**Issue by sarathsp06** [bazil/fuse#205]
The [HandleRead](https://github.com/bazil/fuse/blob/master/fuseutil/fuseutil.go#L9) panics if the `resp.Data` is nil or not big enough to hold `data`

**Comment by tv42** [comment]
`resp.Data` cannot be nil:

```
		s := &fuse.ReadResponse{Data: make([]byte, 0, r.Size)}
```

Where do you see a panic in HandleRead? It's routinely called with `data` larger than `resp.Data`.

**Comment by tv42** [comment]
Not enough information given to help you -> closing this issue.

Also, the kernel decides how much data it wants, you can't return more then `ReadRequest.Size` bytes.
