### ISSUE TITLE
FreeBSD  mount_fusefs: exit status 71 

### ISSUE THREAD

**Issue by doubleddav** [bazil/fuse#206]
Hi,

There appear to be issues on FreeBSD (tested on 11 and 12) using the fuse.AllowOther() option.

Using the helloworld example, I was able to successfully compile and “mount” the example as expected.

By adding fuse.AllowOther(), compiling and running again I get the following:
`mount helper error: mount_fusefs: /dev/fuse on /tank/onedrive: Operation not permitted Fatal error: failed to mount FUSE fs: mount_fusefs: exit status 71`

Below is a snippet from hello.go that I edited
```
func main() {
        flag.Usage = usage
        flag.Parse()

        if flag.NArg() != 1 {
                usage()
                os.Exit(2)
        }
        mountpoint := flag.Arg(0)

        c, err := fuse.Mount(
                mountpoint,
                fuse.FSName("helloworld"),
                fuse.Subtype("hellofs"),
                fuse.LocalVolume(),
                fuse.VolumeName("Hello world!"),
                fuse.AllowOther(),
        )


```

We have found this as a result using rclone to mount remote cloud storage as a non-root user. I have raised a bug there as well which can be found here: https://github.com/ncw/rclone/issues/2828

**Comment by animosity22** [comment]
I was testing on FreeBSD 12 and hit the same issue as well.

**Comment by tv42** [comment]
Were you root? https://www.freebsd.org/cgi/man.cgi?query=mount_fusefs&sektion=8&n=1

'''
 	     allow_other
		     Do	not apply STRICT ACCESS	POLICY.	 Only root can use
		     this option.
'''

**Comment by tv42** [comment]
Confirmed to work when run as root. That's a FreeBSD security decision, nothing I can do here. At least the error message they deem to print says permission denied.
