### ISSUE TITLE
go get - unrecognized import path bazil.org/fuse

### ISSUE THREAD

**Issue by kkbachu** [bazil/fuse#207]
go: bazil.org/fuse@v0.0.0-20180421153158-65cc252bf669: unrecognized import path "bazil.org/fuse" (https fetch: Get https://bazil.org/fuse?go-get=1: read tcp 105.133.6.182:35344->104.28.7.28:443: read: connection reset by peer)

go version go1.12 linux/amd64

**Comment by kkbachu** [comment]
Anyone knows what's going on here? - I can't really get it to work. I googled up, found nothing more than setting GOROOT and GOPATH. go env has these set but I didn't explicitly set them in the shell.

go get bazil.org/fuse
package bazil.org/fuse: unrecognized import path "bazil.org/fuse" (https fetch: Get https://bazil.org/fuse?go-get=1: read tcp 105.133.6.182:36482->104.28.7.28:443: read: connection reset by peer)

**Comment by tv42** [comment]
Something funky with the hosting. You can always do

```
mkdir -p $GOPATH/src/bazil.org
cd $GOPATH/src/bazil.org
git clone https://github.com/bazil/fuse
```

**Comment by tv42** [comment]
Looks like you're having issues connecting to the Cloudflare CDN. Works fine here, is probably transient, and very much out of my control. Unless others see the same problem, this is just Internet as we know it.

**Comment by kkbachu** [comment]
> Looks like you're having issues connecting to the Cloudflare CDN. Works fine here, is probably transient, and very much out of my control. Unless others see the same problem, this is just Internet as we know it.

Thank you for looking into it. 
For the last 2 days, I have been trying to 'go get bazil.org/fuse' working. Finally, ended up commenting it out and it worked while building restic.

Not sure whether its a connection issue or hosting issue. Living with the workaround you gave me for now ;-)

**Comment by fiorix** [comment]
Having the same issue here.

**Comment by jayschwa** [comment]
HTTPS is redirecting to HTTP, which the `go` tool dislikes:
```
go get all: unrecognized import path "bazil.org/fuse" (https fetch: Get http://bazil.org/fuse/?go-get=1: redirected from secure URL https://bazil.org/fuse?go-get=1 to insecure URL http://bazil.org/fuse/?go-get=1)
```
```
$ gotip version
go version devel +4cd6c3b Wed May 8 16:00:05 2019 +0000 linux/amd64
```
