### ISSUE TITLE
GenerateDynamicInode can generate root ID

### ISSUE THREAD

**Issue by hanwen** [bazil/fuse#208]
see https://github.com/bazil/fuse/blob/master/fs/serve.go#L1551

it looks as if this might generate node ID 1 which is reserved for the root directory.

**Comment by tv42** [comment]
Oh yes, you're right. I've been often overriding this in my own apps, because I've had both static and dynamic inodes, and to keep them separate there I always set the high bit on dynamic inodes -- so I haven't thought about this much. Fix should be easy.
