### ISSUE TITLE
NodeCreator example?

### ISSUE THREAD

**Issue by anderspitman** [bazil/fuse#213]
Hi, generally I've found the documentation very helpful in getting things working. However, I'm at a loss with implementing the Create function. It's unclear to me what is required for it to work. It returns both a Node and Handle, does that mean I should return the same object twice (ie Files and Directories implement both Node and Handle). Are there attributes of CreateResponse that must be set by me, or are the defaults sufficient?

**Comment by anderspitman** [comment]
I found the following example in the keybase kbfs repo:

https://github.com/keybase/client/blob/d1a75ea951f0c9d3b7ab2485b504fa80845bc4a2/go/kbfs/libfuse/dir.go#L645

Apparently you do return the same object for both the Node and Handle, and it's not necessary to modify the CreateResponse. Seems to be working for me.

**Comment by tv42** [comment]
Create creates a node and open it (atomically). Whether your fs makes each Node implement Handle or not is completely up to you; you could have multiple separate Handles for one Node. Handle is where to store per-open file state. Consider for example a filesystem where you can read a file to see how manieth opener you are; that is `cat counter; cat counter; cat counter` would say 1, 2, 3 -- except now consider concurrent access, file handles that are kept open for longer, and re-reading the same open file multiple times. For that kind of a trick, the natural thing would be to have Node store the atomic counter, each Open increment that and store the received value in the Handle. Another example of a Handle might be per-user authentication to a remote service.

Relatively simple Create example where Nodes also serve as Handles:
https://github.com/bazil/bolt-mount/blob/3043e5af5e37349e84db7a68e3f74b959def62df/dir.go#L175-L193
