### ISSUE TITLE
Unmount in hello example

### ISSUE THREAD

**Issue by husio** [bazil/fuse#214]
Without any knowledge about FUSE I have started by running the [`examples/hellofs`](https://github.com/bazil/fuse/tree/master/examples/hellofs). 

Running the example, leaves the used by `hellofs` directory broken:
```
$ ls /tmp/ -l
ls: cannot access '/tmp/testfs_2': Socket not connected
ls: cannot access '/tmp/testfs_1': Socket not connected
# ...
d????????? ? ?     ?         ?            ? testfs_1
d????????? ? ?     ?         ?            ? testfs_2
```

I have narrowed the example to the below code.

```go
package main

import (
        "os"

        "bazil.org/fuse"
        _ "bazil.org/fuse/fs/fstestutil"
)

func main() {
        c, err := fuse.Mount(os.Args[1])
        if err != nil {
                panic(err)
        }
        fuse.Unmount(os.Args[1])
        c.Close()
}
```

Adding `fuse.Unmount` makes the used by FUSE directory operational again.

What do you think about:
- adding the `fuse.Unmount` call to the exmaple
- updating the API documentation to include information when to call `fulse.Unmount`

I am still not completely sure if I should call `fuse.Unmount` before or after `c.Close`.

**Comment by tv42** [comment]
There's not much point mounting and immediately unmounting a filesystem; you leave no time to observe it. Your version of the example also completely misses the role of `fs.Serve`.

Let the process run. Look at the filesystem. When you're done, unmount it like you do with all FUSE filesystems; on Linux, that's `fusermount -u /my/mount/point`. Compare to e.g. sshfs; same thing.

The `Unmount` function is only used for triggering the `fusermount` from inside the FUSE server process. That's pretty rare. It mostly only happens with unit tests.
