### ISSUE TITLE
Video streaming performance with HTTP backend?

### ISSUE THREAD

**Issue by anderspitman** [bazil/fuse#215]
My backend is an HTTP server that supports Range requests for requesting specific byte ranges of files. I have some hosted MP4 video files. I'm attempting to watch the video through fuse using VLC. It's working, but performance is terrible (~30 seconds per video frame). I believe the bottleneck is the many HTTP requests. It appears that fuse is using read sizes of 4096.

I tried `fuse.MaxReadahead(128*1024)` as suggested in #172, but it still appears to be using 4k. Is there any way to force a larger read size, or do you have any general performance suggestions? Are there any known projects that are successfully streaming video over a network?

**Comment by anderspitman** [comment]
It's certainly possible that VLC itself is requesting chunks of 4096, but I'd think it would be tuned for working with NFS, etc.

**Comment by tv42** [comment]
One of the first things I did once https://bazil.org started working was watch Big Buck Bunny over wifi.
There might be a way to get larger reads, but 1) I don't have an immediate answer, I'd have to set up a test for test 2) ultimately you're just not in control.

You could decouple your HTTP behavior from FUSE. For inspiration, see how they use groupcache in https://talks.golang.org/2013/oscon-dl.slide

**Comment by anderspitman** [comment]
@tv42 just an update. I did indeed have some bugs in my range handling on the server. I'm now able to stream video over FUSE at about 10Mbps. Do you happen to remember about what bitrates you've achieved in the past?

I think I'm good to go for the short term. Long term if necessary I'll probably try caching larger chunks from the server as you suggested. Thanks for that.

**Comment by tv42** [comment]
I didn't really measure bitrate, it did whatever was needed to stream 1080p BBB at faster than realtime, seeking around, etc.

**Comment by tv42** [comment]
I marked this invalid because it seems the real culprit was HTTP range handling.
