### ISSUE TITLE
Inferior performance on Linux compared on macOS, too many Syscalls

### ISSUE THREAD

**Issue by eliezedeck** [bazil/fuse#216]
Hi,

I'm not sure why, but compared to my test on macOS, the library is considerably slower on Linux than on macOS. When I tried to do basic profiling, I saw that major time consumption is doing Syscalls.

May be a buffer difference/use on both platforms? I don't know. I'd like to debug, but I'm not sure where to start without an initial pointers.

Thanks

**Comment by MikaelSmith** [comment]
It'd be useful to have a description of the profiling you were doing so others can reproduce it and to provide context for what might be related to the performance. Without that all I can think to offer are general Linux profiling pointers. Look at http://www.pixelbeat.org/programming/profiling/ or http://www.brendangregg.com/perf.html for ideas.

Where I might start is getting a count of how many syscalls you see for the same operations on macOS and Linux, and flame graphs of how long each spends on them.

**Comment by tv42** [comment]
My experience says Linux is the fastest FUSE platform (being the origin of FUSE and all, the kernel interface looks a lot like Linux internals), and macOS was never particularly fast. Please provide more information, how you're measuring, what your FUSE filesystem is, etc. For example, what if your filesystem logic responds to requests slower on Linux than macOS, for some reason.

**Comment by tv42** [comment]
Can't do anything here. If you want help, you need to ask a complete question.
