### ISSUE TITLE
Trouble implementing mv

### ISSUE THREAD

**Issue by anderspitman** [bazil/fuse#218]
I'm trying to get `mv` to work. My fuse mount is at `mnt`. I tried implementing `NodeRenamer`, but it doesn't seem to be getting called.

Running the following command:

```
mv mnt/f1.txt mnt/f2.txt
```

yields the following debug trace:

```
<- Lookup [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f1.txt"
-> [ID=0x4] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=38141767354195187 size=9 mode=-rw-rw-rw-}
<- Lookup [ID=0x6 Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f2.txt"
-> [ID=0x6] Lookup error=ENOENT
<- Lookup [ID=0x8 Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f2.txt"
-> [ID=0x8] Lookup error=ENOENT
<- Lookup [ID=0xa Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f2.txt"
-> [ID=0xa] Lookup error=ENOENT
<- Rename [ID=0xc Node=0x1 Uid=1000 Gid=1000 Pid=283187] from "f1.txt" to dirnode 0x1 "f2.txt"
-> [ID=0xc] Rename error=EIO
<- Lookup [ID=0xe Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f2.txt"
-> [ID=0xe] Lookup error=ENOENT
<- Lookup [ID=0x10 Node=0x1 Uid=1000 Gid=1000 Pid=283187] "f2.txt"
-> [ID=0x10] Lookup error=ENOENT
<- Getattr [ID=0x12 Node=0x1 Uid=1000 Gid=1000 Pid=283197] 0x0 fl=0
-> [ID=0x12] Getattr valid=1m0s ino=1 size=0 mode=dr-xr-xr-x
```

Am I missing some other required methods?

**Comment by tv42** [comment]
Best bet is you got the signature of `Rename` wrong. If your FS implementation is called `Foo` (and your methods have the usual pointer receiver), add a line like

```
var _ fs.NodeRenamer = (*Foo)(nil)
```

and see if the compiler yells at you.

**Comment by anderspitman** [comment]
The signature wasn't just wrong; it was embarrassingly wrong. I somehow forgot to even make `Rename` a receiver, so it was basically a free function doing nothing. Sorry for wasting your time.

1. You do bring up a couple small questions for me though. I've seen this syntax before in go code:

```
var _ fs.NodeRenamer = (*Foo)(nil)
```

What does that do exactly, and what's it usually used to accomplish? In this context it looks like it removes the default implementation of the interface, in order to force a compiler error?

2. `NodeRenamer` should be implemented on the directory receiver, right? Why are you resetting it on Foo/Fs here?

Thanks!

**Comment by tv42** [comment]
1. Combines a couple of basic concepts into a neat trick. First, assignments to `_` do nothing. Second, a value of type `*Foo` can be assigned to a variable of the interface type `fs.NodeRenamer` only if `*Foo` iplements that interface. Third, `(*Foo)(nil)` is a pointer of type `*Foo` pointing to nothing. Together, they verify that `*Foo` implements that interface.

2. Not sure what you mean by "resetting on Foo/Fs". The `Rename` method is called on the node it acts upon (what is being renamed), and the arguments tell it its old name, new name, and the new containing directory (which may or may not be its current location).

**Comment by anderspitman** [comment]
Thanks!
