### ISSUE TITLE
panic: opBmap on new FreeBSD 12.1-RELEASE

### ISSUE THREAD

**Issue by ncw** [bazil/fuse#221]
This issue was originally reported on the rclone repo: https://github.com/rclone/rclone/issues/3697

> I just updated my system to FreeBSD 12.1-RELEASE. Along with this release comes some improvements to fusefs, outlined here: https://svnweb.freebsd.org/base?view=revision&revision=352351
> Another notable change is the kernel module loaded is now fusefs.ko instead of fuse.ko

What appears to happen is that something in the new FUSE setup triggers this panic message

https://github.com/bazil/fuse/blob/65cc252bf6691cb3c7014bcb2c8dc29de91e3a7e/fuse.go#L1006-L1007
```
panic: opBmap

goroutine 27 [running]:
github.com/rclone/rclone/vendor/bazil.org/fuse.(*Conn).ReadRequest(0xc00007a3c0, 0x16bac70, 0xc00030e480, 0x191b720, 0xc00011c040)
/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/bazil.org/fuse/fuse.go:1007 +0x5118
github.com/rclone/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve(0xc00030e480, 0x18fdb40, 0xc000114660, 0x0, 0x0)
/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/bazil.org/fuse/fs/serve.go:414 +0x372
github.com/rclone/rclone/cmd/mount.mount.func1(0xc00030e480, 0xc000114660, 0xc00007a3c0, 0xc00007b0e0)
/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/mount/mount.go:98 +0x45
created by github.com/rclone/rclone/cmd/mount.mount
/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/mount/mount.go:97 +0x2ee
```

Any help much appreciated :-)

**Comment by tv42** [comment]
It's some BSD-specific thing, unhandled since the first version of this FUSE library in 2011.

**Comment by RogerAirgood** [comment]
I'm the user who raised the issue on the rclone repo. The directory seems to mount fine, I can ls as usual. As soon as I try to read something (in this test, an md5 on a random file) the mount crashes. Below is a log file:

2019/11/06 18:23:17 DEBUG : rclone: Version "v1.50.1-017-g0eaf5475-beta" starting with parameters ["./rclone" "mount" "-vv" "--debug-fuse" "--allow-other" "--allow-non-empty" "--log-file" "/var/log/rclone.log" "--fast-list" "--vfs-read-chunk-size-limit" "off" "--daemon" "--timeout" "1h" "--daemon-timeout" "0" "cachedrive:" "/mnt/gcache"]
2019/11/06 18:23:17 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/11/06 18:23:17 DEBUG : cachedrive: wrapped gdrive: at root
2019/11/06 18:23:17 INFO : cachedrive: Cache DB path: /root/.cache/rclone/cache-backend/cachedrive.db
2019/11/06 18:23:17 INFO : cachedrive: Cache chunk path: /root/.cache/rclone/cache-backend/cachedrive
2019/11/06 18:23:17 INFO : cachedrive: Chunk Memory: true
2019/11/06 18:23:17 INFO : cachedrive: Chunk Size: 10M
2019/11/06 18:23:17 INFO : cachedrive: Chunk Total Size: 15G
2019/11/06 18:23:17 INFO : cachedrive: Chunk Clean Interval: 1m0s
2019/11/06 18:23:17 INFO : cachedrive: Workers: 4
2019/11/06 18:23:17 INFO : cachedrive: File Age: 2d
2019/11/06 18:23:17 DEBUG : Adding path "cache/expire" to remote control registry
2019/11/06 18:23:17 DEBUG : Adding path "cache/stats" to remote control registry
2019/11/06 18:23:17 DEBUG : Adding path "cache/fetch" to remote control registry
2019/11/06 18:23:17 DEBUG : Cache remote cachedrive:: Mounting on "/mnt/gcache"
2019/11/06 18:23:17 DEBUG : gdrive: Loaded invalid token from config file - ignoring
2019/11/06 18:23:17 DEBUG : Cache remote cachedrive:: subscribing to ChangeNotify
2019/11/06 18:23:17 DEBUG : Adding path "vfs/forget" to remote control registry
2019/11/06 18:23:17 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/11/06 18:23:17 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/11/06 18:23:17 DEBUG : : Root:
2019/11/06 18:23:17 DEBUG : : >Root: node=/, err=
2019/11/06 18:23:17 DEBUG : gdrive: Saved new token in config file
2019/11/06 18:23:20 DEBUG : fuse: <- Getattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=4107] 0x0 fl=0
2019/11/06 18:23:20 DEBUG : /: Attr:
2019/11/06 18:23:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x2] Getattr valid=1s ino=1 size=0 mode=drwxr-xr-x
2019/11/06 18:23:20 DEBUG : fuse: <- Access [ID=0x3 Node=0x1 Uid=0 Gid=0 Pid=4107] mask=0x4
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x3] Access
2019/11/06 18:23:20 DEBUG : fuse: <- Open [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=4107] dir=true fl=OpenReadOnly
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x4] Open 0x1 fl=0
2019/11/06 18:23:20 DEBUG : fuse: <- Statfs [ID=0x5 Node=0x1 Uid=0 Gid=0 Pid=4107]
2019/11/06 18:23:20 DEBUG : : Statfs:
2019/11/06 18:23:20 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:273663663445 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x5] Statfs blocks=274877906944/273663663445/274877906944 files=1000000000/1000000000 bsize=4096 frsize=4096 namelen=255
2019/11/06 18:23:20 DEBUG : fuse: <- Read [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=4107] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:20 DEBUG : /: ReadDirAll:
2019/11/06 18:23:20 DEBUG : Cache remote cachedrive:: list ''
2019/11/06 18:23:20 DEBUG : : list: warm 99 from cache for: , expiring on: 2019-11-07 02:21:38.810138099 -0400 AST
2019/11/06 18:23:20 DEBUG : : list: cached entries: [redacted]
2019/11/06 18:23:20 DEBUG : /: >ReadDirAll: item=99, err=
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x6] Read 4096
2019/11/06 18:23:20 DEBUG : fuse: <- Read [ID=0x7 Node=0x1 Uid=0 Gid=0 Pid=4107] 0x1 4096 @0xfa8 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x7] Read 728
2019/11/06 18:23:20 DEBUG : fuse: <- Read [ID=0x8 Node=0x1 Uid=0 Gid=0 Pid=4107] 0x1 4096 @0x1280 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:20 DEBUG : fuse: -> [ID=0x8] Read 0
2019/11/06 18:23:31 DEBUG : fuse: <- Access [ID=0x9 Node=0x1 Uid=0 Gid=0 Pid=4085] mask=0x4
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0x9] Access
2019/11/06 18:23:31 DEBUG : fuse: <- Open [ID=0xa Node=0x1 Uid=0 Gid=0 Pid=4085] dir=true fl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xa] Open 0x2 fl=0
2019/11/06 18:23:31 DEBUG : fuse: <- Statfs [ID=0xb Node=0x1 Uid=0 Gid=0 Pid=4085]
2019/11/06 18:23:31 DEBUG : : Statfs:
2019/11/06 18:23:31 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:273663663445 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xb] Statfs blocks=274877906944/273663663445/274877906944 files=1000000000/1000000000 bsize=4096 frsize=4096 namelen=255
2019/11/06 18:23:31 DEBUG : fuse: <- Read [ID=0xc Node=0x1 Uid=0 Gid=0 Pid=4085] 0x2 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : /: ReadDirAll:
2019/11/06 18:23:31 DEBUG : /: >ReadDirAll: item=99, err=
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xc] Read 4096
2019/11/06 18:23:31 DEBUG : fuse: <- Read [ID=0xd Node=0x1 Uid=0 Gid=0 Pid=4085] 0x2 4096 @0xfa8 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xd] Read 728
2019/11/06 18:23:31 DEBUG : fuse: <- Read [ID=0xe Node=0x1 Uid=0 Gid=0 Pid=4085] 0x2 4096 @0x1280 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xe] Read 0
2019/11/06 18:23:31 DEBUG : fuse: <- Access [ID=0xf Node=0x1 Uid=0 Gid=0 Pid=4085] mask=0x1
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0xf] Access
2019/11/06 18:23:31 DEBUG : fuse: <- Lookup [ID=0x10 Node=0x1 Uid=0 Gid=0 Pid=4085] "Functions.7z"
2019/11/06 18:23:31 DEBUG : /: Lookup: name="Functions.7z"
2019/11/06 18:23:31 DEBUG : /: >Lookup: node=Functions.7z, err=
2019/11/06 18:23:31 DEBUG : Functions.7z: Attr:
2019/11/06 18:23:31 DEBUG : Functions.7z: >Attr: a=valid=1s ino=0 size=2881237 mode=-rw-r--r--, err=
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0x10] Lookup 0x2 gen=0 valid=1s attr={valid=1s ino=8590050102649675312 size=2881237 mode=-rw-r--r--}
2019/11/06 18:23:31 DEBUG : fuse: <- Access [ID=0x11 Node=0x1 Uid=0 Gid=0 Pid=4109] mask=0x1
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0x11] Access
2019/11/06 18:23:31 DEBUG : fuse: <- Access [ID=0x12 Node=0x2 Uid=0 Gid=0 Pid=4109] mask=0x4
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0x12] Access
2019/11/06 18:23:31 DEBUG : fuse: <- Open [ID=0x13 Node=0x2 Uid=0 Gid=0 Pid=4109] dir=false fl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : Functions.7z: Open: flags=OpenReadOnly
2019/11/06 18:23:31 DEBUG : Functions.7z: Open: flags=O_RDONLY
2019/11/06 18:23:31 DEBUG : Functions.7z: >Open: fd=Functions.7z (r), err=
2019/11/06 18:23:31 DEBUG : Functions.7z: >Open: fh=&{Functions.7z (r)}, err=
2019/11/06 18:23:31 DEBUG : fuse: -> [ID=0x13] Open 0x3 fl=0
2019/11/06 18:23:31 DEBUG : fuse: <- Read [ID=0x14 Node=0x2 Uid=0 Gid=0 Pid=4109] 0x3 65536 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2019/11/06 18:23:31 DEBUG : &{Functions.7z (r)}: Read: len=65536, offset=0
2019/11/06 18:23:31 DEBUG : Functions.7z: ChunkedReader.openRange at 0 length 134217728
2019/11/06 18:23:32 DEBUG : Functions.7z: moving offset set from 0 to 0
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 0 length 4096 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 4096 length 8192 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 12288 length 16384 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 28672 length 32768 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 61440 length 65536 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : &{Functions.7z (r)}: >Read: read=65536, err=
2019/11/06 18:23:32 DEBUG : fuse: -> [ID=0x14] Read 65536
2019/11/06 18:23:32 DEBUG : Functions.7z: ChunkedReader.Read at 126976 length 131072 chunkOffset 0 chunkSize 134217728
2019/11/06 18:23:32 DEBUG : fuse: <- Getattr [ID=0x15 Node=0x2 Uid=0 Gid=0 Pid=4109] 0x0 fl=0
2019/11/06 18:23:32 DEBUG : Functions.7z: Attr:
2019/11/06 18:23:32 DEBUG : Functions.7z: >Attr: a=valid=1s ino=0 size=2881237 mode=-rw-r--r--, err=
2019/11/06 18:23:32 DEBUG : fuse: -> [ID=0x15] Getattr valid=1s ino=8590050102649675312 size=2881237 mode=-rw-r--r--
panic: opBmap

goroutine 14 [running]:
github.com/rclone/rclone/vendor/bazil.org/fuse.(*Conn).ReadRequest(0xc0000aed80, 0x16bac70, 0xc0001be0c0, 0x191b720, 0xc000120840)
/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/bazil.org/fuse/fuse.go:1007 +0x5118
github.com/rclone/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve(0xc0001be0c0, 0x18fdb40, 0xc0002d2840, 0x0, 0x0)
/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/bazil.org/fuse/fs/serve.go:414 +0x372
github.com/rclone/rclone/cmd/mount.mount.func1(0xc0001be0c0, 0xc0002d2840, 0xc0000aed80, 0xc000079500)
/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/mount/mount.go:98 +0x45
created by github.com/rclone/rclone/cmd/mount.mount
/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/mount/mount.go:97 +0x2ee

**Comment by ncw** [comment]
@tv42 wrote:
> It's some BSD-specific thing, unhandled since the first version of this FUSE library in 2011.

I understand from @RogerAirgood that `rclone mount` was working with previous versions of FreeBSD and this failure is new behavior to FreeBSD 12.1 which was only released on 4th November 2019 - is that correct?

Can we ignore this message from the kernel somehow instead of panic-ing?

**Comment by tv42** [comment]
> Can we ignore this message from the kernel somehow instead of panic-ing?

First step is to figure out what "bmap" is. Until that's known, it can't be assumed to be safe to ignore.

**Comment by RogerAirgood** [comment]
Yes, it is correct that this issue only appeared with FreeBSD 12.1-RELEASE. It works fine in previous versions.

**Comment by ncw** [comment]
Here is what the docs say about bmap: https://libfuse.github.io/doxygen/structfuse__operations.html#afb5d953d0aca9d859480abd470abd754

> Map block index within file to block index within device
>
> Note: This makes sense only for block device backed filesystems mounted with the 'blkdev' option

We didn't use the `blkdev` option so maybe this is a bug in FreeBSD 12.1-RELEASE which shouldn't really be issuing that?

**Comment by asomers** [comment]
FreeBSD's FUSE maintainer here.  I think I can answer all of your questions.

* The purpose of `FUSE_BMAP` is to let the kernel know something about the layout of the file on the media.  The kernel uses that information for purposes like scheduling and aggregating I/O.
* FreeBSD 12.0 and earlier did not use `FUSE_BMAP`.  That's why the crash only started with 12.1.
* `blkdev` is a Linux-only mount option.  I don't know why Linux needs it, but FreeBSD doesn't.
* `FUSE_BMAP` is an optional opcode.  Like other optional opcodes, the FUSE server can simply return `ENOSYS` to tell the kernel that it isn't supported for this mountpoint.  After the first time it returns `ENOSYS`, the kernel will never again issue `FUSE_BMAP` for the lifetime of that mountpoint.

**Comment by ncw** [comment]
Thanks for clearing that up @asomers - very helpful :-)

I would guess a patch like this

```diff
diff --git a/fuse.go b/fuse.go
index 7dc70f9..55e9901 100644
--- a/fuse.go
+++ b/fuse.go
@@ -1004,7 +1004,7 @@ loop:
 		}
 
 	case opBmap:
-		panic("opBmap")
+		return nil, ENOSYS
 
 	case opDestroy:
 		req = &DestroyRequest{
```

Would fix it....

@RogerAirgood I made a version of rclone with that patch in so you can see if it works...

https://beta.rclone.org/branch/v1.50.1-036-g01fa2bc5-fix-freebsd-mount-beta/ (uploaded in 15-30 mins)

**Comment by RogerAirgood** [comment]
Thanks for the patch @ncw 
I just tried it out using the same test methodology, listing the directory contents and running md5 on a file. It still crashes, though differently. Logs with --debug-fuse below, let me know if you need more: 


2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x1d] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x1e Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0xfb0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x1e] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x1f Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x1f08 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x1f] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x20 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x2ee8 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x20] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x21 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x3de0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x21] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x22 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x4d58 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x22] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x23 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x5d28 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x23] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x24 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x6cb8 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x24] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x25 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x7c60 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x25] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x26 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x8c18 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x26] Read 4096
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x27 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0x9bf0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x27] Read 3824
2019/11/13 11:50:20 DEBUG : fuse: <- Read [ID=0x28 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 4096 @0xaae0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x28] Read 0
2019/11/13 11:50:20 DEBUG : fuse: <- Release [ID=0x29 Node=0x2 Uid=0 Gid=0 Pid=903] 0x4 fl=OpenReadOnly rfl=0 owner=0x387
2019/11/13 11:50:20 DEBUG : fuse: -> [ID=0x29] Release
2019/11/13 11:50:44 DEBUG : fuse: <- Access [ID=0x2a Node=0x1 Uid=0 Gid=0 Pid=838] mask=0x4
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2a] Access
2019/11/13 11:50:44 DEBUG : fuse: <- Open [ID=0x2b Node=0x1 Uid=0 Gid=0 Pid=838] dir=true fl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2b] Open 0x4 fl=0
2019/11/13 11:50:44 DEBUG : fuse: <- Statfs [ID=0x2c Node=0x1 Uid=0 Gid=0 Pid=838]
2019/11/13 11:50:44 DEBUG : : Statfs:
2019/11/13 11:50:44 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:273607647093 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2c] Statfs blocks=274877906944/273607647093/274877906944 files=1000000000/1000000000 bsize=4096 frsize=4096 namelen=255
2019/11/13 11:50:44 DEBUG : fuse: <- Read [ID=0x2d Node=0x1 Uid=0 Gid=0 Pid=838] 0x4 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : /: ReadDirAll:
2019/11/13 11:50:44 DEBUG : /: >ReadDirAll: item=101, err=<nil>
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2d] Read 4096
2019/11/13 11:50:44 DEBUG : fuse: <- Read [ID=0x2e Node=0x1 Uid=0 Gid=0 Pid=838] 0x4 4096 @0xfa8 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2e] Read 792
2019/11/13 11:50:44 DEBUG : fuse: <- Read [ID=0x2f Node=0x1 Uid=0 Gid=0 Pid=838] 0x4 4096 @0x12c0 dir=true fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x2f] Read 0
2019/11/13 11:50:44 DEBUG : fuse: <- Access [ID=0x30 Node=0x1 Uid=0 Gid=0 Pid=838] mask=0x1
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x30] Access
2019/11/13 11:50:44 DEBUG : fuse: <- Lookup [ID=0x31 Node=0x1 Uid=0 Gid=0 Pid=838] "Functions.7z"
2019/11/13 11:50:44 DEBUG : /: Lookup: name="Functions.7z"
2019/11/13 11:50:44 DEBUG : /: >Lookup: node=Functions.7z, err=<nil>
2019/11/13 11:50:44 DEBUG : Functions.7z: Attr:
2019/11/13 11:50:44 DEBUG : Functions.7z: >Attr: a=valid=1s ino=0 size=2881237 mode=-rw-r--r--, err=<nil>
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x31] Lookup 0x3 gen=0 valid=1s attr={valid=1s ino=8590050102649675312 size=2881237 mode=-rw-r--r--}
2019/11/13 11:50:44 DEBUG : fuse: <- Access [ID=0x32 Node=0x1 Uid=0 Gid=0 Pid=906] mask=0x1
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x32] Access
2019/11/13 11:50:44 DEBUG : fuse: <- Access [ID=0x33 Node=0x3 Uid=0 Gid=0 Pid=906] mask=0x4
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x33] Access
2019/11/13 11:50:44 DEBUG : fuse: <- Open [ID=0x34 Node=0x3 Uid=0 Gid=0 Pid=906] dir=false fl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : Functions.7z: Open: flags=OpenReadOnly
2019/11/13 11:50:44 DEBUG : Functions.7z: Open: flags=O_RDONLY
2019/11/13 11:50:44 DEBUG : Functions.7z: >Open: fd=Functions.7z (r), err=<nil>
2019/11/13 11:50:44 DEBUG : Functions.7z: >Open: fh=&{Functions.7z (r)}, err=<nil>
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x34] Open 0x5 fl=0
2019/11/13 11:50:44 DEBUG : fuse: <- Read [ID=0x35 Node=0x3 Uid=0 Gid=0 Pid=906] 0x5 65536 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2019/11/13 11:50:44 DEBUG : &{Functions.7z (r)}: Read: len=65536, offset=0
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.openRange at 0 length 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: moving offset set from 0 to 0
2019/11/13 11:50:44 DEBUG : Functions.7z: moving offset set from 0 to 0
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 0 length 4096 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 4096 length 8192 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 12288 length 16384 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 28672 length 32768 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 61440 length 65536 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : Functions.7z: ChunkedReader.Read at 126976 length 131072 chunkOffset 0 chunkSize 134217728
2019/11/13 11:50:44 DEBUG : &{Functions.7z (r)}: >Read: read=65536, err=<nil>
2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x35] Read 65536
2019/11/13 11:50:44 Fatal error: failed to umount FUSE fs: function not implemented

**Comment by ncw** [comment]
> Thanks for the patch @ncw
> I just tried it out using the same test methodology, listing the directory contents and running md5 on a file. It still crashes, though differently. Logs with --debug-fuse below, let me know if you need more:

> 2019/11/13 11:50:44 DEBUG : fuse: -> [ID=0x35] Read 65536
> 2019/11/13 11:50:44 Fatal error: failed to umount FUSE fs: function not implemented

It isn't clear to me what happened there!  I probably need to make a FreeBSD VM to experiment some more. Rclone just stopped apparently...

@tv42 would you like the above patch as a pull request?  Or shall I investigate further?

**Comment by ncw** [comment]
@RogerAirgood here is a better patch which I've tested on a FreeBSD 12.1 VM - can you have a go

https://beta.rclone.org/branch/v1.50.1-036-g6f98e6c9-fix-freebsd-mount-beta/ (uploaded in 15-30 mins)

This is just

```patch
diff --git a/vendor/bazil.org/fuse/fuse.go b/vendor/bazil.org/fuse/fuse.go
index 7dc70f9e1..ccbcb8d09 100644
--- a/vendor/bazil.org/fuse/fuse.go
+++ b/vendor/bazil.org/fuse/fuse.go
@@ -1004,7 +1004,7 @@ loop:
                }
 
        case opBmap:
-               panic("opBmap")
+               goto unrecognized
 
        case opDestroy:
                req = &DestroyRequest{
```

If that works I'll send it as a pull request!

**Comment by RogerAirgood** [comment]
@ncw Great Stuff!

I gave it a go and it passed all my tests that were causing issues prior. Haven't done any serious testing but it seems to read and write fine, at least for my workload. 

Appreciate the prompt assistance!

**Comment by ncw** [comment]
Thanks for testing @RogerAirgood 

I've sent a PR #222 with that small fix in @tv42

**Comment by jkoopmann** [comment]
Sorry to barge in @ncw: I tested with v1.50.2-056-ge14d968f-beta and am seeing the same "old" behavior. Is the fix not part of this (will try with the other link you mentioned in a minute).

**Comment by ncw** [comment]
I made a vendor patch as a test which should work but I need #222 merged here before I can fix rclone properly!

**Comment by tv42** [comment]
I made a slightly more verbose commit. The weirdest thing is that I still can't trigger this on my FreeBSD 12.1-RELEASE-p1 test vm -- though I haven't done much more than ran the unit tests with it. I'd appreciate if someone could isolate why exactly it triggered for some users, what was different in the operations submitted.
