### ISSUE TITLE
errors.As not supported on go < 1.13

### ISSUE THREAD

**Issue by felixbuenemann** [bazil/fuse#236]
The commit 3bebd277fa844a81aaabccac0c6ee81b5e59205b broke support for golang < 1.13.

Is there any way to implement it without breaking backwards compatibility?

**Comment by tv42** [comment]
And go.mod explicitly states `go 1.13`.

Go 1.14 will likely be released on February, at which point 1.12 is no longer supported. Please upgrade more often, for your own benefit. https://github.com/golang/go/wiki/Go-Release-Cycle
