### ISSUE TITLE
How to preserve the order of the request processes

### ISSUE THREAD

**Issue by roy2220** [bazil/fuse#241]
Here is the situation that I encountered:
  - The incoming requests in order:
    1. request 0xb2 -- to closedir `foo`
    2. request 0xb3 -- to rmdir `foo`
  - But the requests were processed in order:
    1. request 0xb3 -- rmdir `foo` failed, `foo` is still open
    2. request 0xb2 -- closedir `foo` succeeded.

I check the source and find out that each request was processed in an isolated goroutine (for better concurrent performance?), so the order of the request processes could not be guaranteed.

Are there any suggestions to fix this case?

**Comment by tv42** [comment]
> rmdir `foo` failed, `foo` is still open

Well there's your problem. That's not how a unix filesystem behaves. Open handles can outlive the directory entry.

The kernel will enforce ordering when there is a dependency (it will not submit a request before it gets a response that is depended on). We actually can't break that ordering, purely in userspace. But it follows the Linux VFS rules, so roughly UNIX semantics.

Nothing to be done here, as far as I know. You simply can't make a non-UNIX filesystem on a UNIX.

What's the actual problem being solved?

**Comment by roy2220** [comment]
@tv42 I get it now, thanks for the information!
