### ISSUE TITLE
fuse high level API support?

### ISSUE THREAD

**Issue by xrefft** [bazil/fuse#242]
We observed that this package only has fuse.go, and does not distinguish between high level or low level APIs.
Will the high level interface be supported in the future and the inode will be encapsulated?

**Comment by MikaelSmith** [comment]
Did you look at https://godoc.org/bazil.org/fuse/fs? I consider it the higher level API.

**Comment by tv42** [comment]
What do you mean by "high level" vs "low level"?

If https://godoc.org/bazil.org/fuse/fs is not "high level" enough for you, you really don't want to write a FUSE filesystem; file systems are pretty low level by definition. You are expected to understand Linux VFS design and concepts.

**Comment by tv42** [comment]
Closing drive-by issue with nothing concrete in it.
