### ISSUE TITLE
Current directory disappears after attr timeout expires

### ISSUE THREAD

**Issue by ncw** [bazil/fuse#250]
An rclone user discovered that getcwd() fails in subdirectories of rclone mounts https://github.com/rclone/rclone/issues/4104

I've managed to track this down a bit more precisely.

To reproduce with rclone first mount a local directory

```
mkdir -p /tmp/src/sub
rclone mount /tmp/src /mnt/tmp
```

In another window

```
$ cd /mnt/tmp/sub ; ls -l /proc/self/cwd
lrwxrwxrwx 1 ncw ncw 0 Apr 29 15:55 /proc/self/cwd -> /mnt/tmp/sub
$
$ # wait a few seconds
$ ls -l /proc/self/cwd
rwxrwxrwx 1 ncw ncw 0 Apr 29 15:55 /proc/self/cwd -> '/mnt/tmp/sub (deleted)'
```

`/proc/self/cwd` being deleted means that for example the `getcwd()` system call fails

```
$ python -c 'import os; print os.getcwd()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory
```

Rclone sets attribute timeouts of 1 second by default and if you increase the attribute timeout (with `--attr-timeout`) then the current working directory lasts for longer so it is related to that attribute timeout.

Rclone has a another mount command (you compile it using `--tags cmount`) using libfuse and this does **not** have the same problem which is puzzling, making me think it is something that this library is doing, or maybe something extra that libfuse does.

I could fix this by increasing the attribute timeout (maybe just for directories) but I don't want to make it very large otherwise changes won't be noticed.

Any ideas or suggestions much appreciated - thanks!

**Comment by tv42** [comment]
That sounds like your implementation of Lookup is not finding the same Node.

**Comment by ncw** [comment]
This is what I see in the logs (with `-vv --debug-fuse` flags)

When the `ls` succeeds

```
2020/04/29 17:11:22 DEBUG : fuse: <- Lookup [ID=0x10 Node=0x1 Uid=1000 Gid=1000 Pid=38827] "sub"
2020/04/29 17:11:22 DEBUG : /: Lookup: name="sub"
2020/04/29 17:11:22 DEBUG : /: >Lookup: node=sub/, err=<nil>
2020/04/29 17:11:22 DEBUG : sub/: Attr: 
2020/04/29 17:11:22 DEBUG : sub/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2020/04/29 17:11:22 DEBUG : fuse: -> [ID=0x10] Lookup 0x3 gen=0 valid=1s attr={valid=1s ino=5826373571668926310 size=0 mode=drwxrwxr-x}
2020/04/29 17:11:22 DEBUG : fuse: <- Lookup [ID=0x14 Node=0x1 Uid=1000 Gid=1000 Pid=38827] "sub"
2020/04/29 17:11:22 DEBUG : fuse: <- Forget [ID=0x12 Node=0x3 Uid=0 Gid=0 Pid=0] 1
2020/04/29 17:11:22 DEBUG : /: Lookup: name="sub"
2020/04/29 17:11:22 DEBUG : fuse: -> [ID=0x12] Forget
2020/04/29 17:11:22 DEBUG : /: >Lookup: node=sub/, err=<nil>
2020/04/29 17:11:22 DEBUG : sub/: Attr: 
2020/04/29 17:11:22 DEBUG : sub/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2020/04/29 17:11:22 DEBUG : fuse: -> [ID=0x14] Lookup 0x3 gen=1 valid=1s attr={valid=1s ino=5826373571668926310 size=0 mode=drwxrwxr-x}
```

When it fails - it appears to be looking up "sub (deleted)"!

```
2020/04/29 17:11:35 DEBUG : fuse: <- Lookup [ID=0x16 Node=0x1 Uid=1000 Gid=1000 Pid=38831] "sub (deleted)"
2020/04/29 17:11:35 DEBUG : /: Lookup: name="sub (deleted)"
2020/04/29 17:11:35 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2020/04/29 17:11:35 DEBUG : fuse: -> [ID=0x16] Lookup error=ENOENT
```

There is nothing else in the fuse logs and nothing between those two logs.

**Comment by tv42** [comment]
Whatever application this is decided to start asking for a directory entry named "sub (deleted)". That's not the FUSE library, and that's not the kernel.

**Comment by tv42** [comment]
So you're following a /proc/PID/fd symlink blindly, and that leads you astray on the filename.

Now, why does /proc/PID/fd think it's deleted?

**Comment by tv42** [comment]
Well, I can reproduce this with a trivial filesystem, so that's good news.

**Comment by ncw** [comment]
> Whatever application this is decided to start asking for a directory entry named "sub (deleted)". That's not the FUSE library, and that's not the kernel.

That is just me running `ls -l` on the symlink

> So you're following a /proc/PID/fd symlink blindly, and that leads you astray on the filename.

Indeed!

> Now, why does /proc/PID/fd think it's deleted?

That is the real problem - I was just demonstrating it with the `ls -l`

> As far as I can read right now, for all the linux kernel cares, " (deleted)" comes from not being included in the kernel in-memory dentry cache (include/dcache.h d_unlinked).

That fits the behaviour perfectly...

> No idea why that Forget was sent, unless perhaps if the system was under severe memory pressure?

No I don't think so.

> Well, I can reproduce this with a trivial filesystem, so that's good news.

:-)

The only clue I can offer is that libfuse works around this somehow. I trawled through its code but I couldn't find its special sauce. You might have more luck being more familiar with the subject area!

**Comment by tv42** [comment]
libfuse does a lot of things I'm very much not willing to do. I like to go by first principles, in this case how does the kernel behave.

So I got it to reproduce twice, then went to lower valid times to trigger it quicker, and now it doesn't trigger even after I restore the source to original state. Seems like a race of some sort.

**Comment by tv42** [comment]
Well, apart from those two initial runs, this really hasn't reproduced for me with a trivial fs. I think I need to run all of rclone to see what's going on.

**Comment by tv42** [comment]
It seems this triggers with bash but not with dash, and I switched to dash because my bash customizations were adding too much noise.

**Comment by tv42** [comment]
Does not trigger: `/bin/bash -c 'cd mnt/sub && /bin/ls -l /proc/self/cwd && sleep 5 && /bin/ls -l /proc/self/cwd'`

Triggers: same steps in an interactive bash session, even `bash --noprofile`.

**Comment by ncw** [comment]
I found when I was making the issue that I could never get it to trigger with

    cd mnt/sub && /bin/ls -l /proc/self/cwd && sleep 5 && /bin/ls -l /proc/self/cwd

I had to do

    cd mnt/sub && /bin/ls -l /proc/self/cwd
    # wait a bit
    /bin/ls -l /proc/self/cwd

I didn't figure out why, but using `&& sleep`` seemed to stop it falling out of the cache.

**Comment by tv42** [comment]
Does not trigger: interactive `bash --noprofile` with PS1 neutralized to remove my git prompt customization.

**Comment by tv42** [comment]
Triggers: `/bin/sh -c 'cd mnt/sub && /bin/ls -l /proc/self/cwd && sleep 1 && /bin/ls -ld ../sub && /bin/ls -l /proc/self/cwd'`

The key to triggering seems to be a new lookup for `sub` that is not recognized as the same node as the previous lookup result.

**Comment by tv42** [comment]
Yeah that's probably a filesystem bug (as in, rclone, and probably my trivial fs too; gonna go validate that next).

```
<- Lookup [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=17132] "sub"
-> [ID=0x4] Lookup 0x2 gen=0 valid=1s attr={valid=1s ino=5826373571668926310 size=0 mode=drwxr-xr-x}
# sub is node 2

<- Access [ID=0x6 Node=0x2 Uid=1000 Gid=1000 Pid=17132] mask=0x1
-> [ID=0x6] Access

# sleep happens here

<- Getxattr [ID=0x8 Node=0x2 Uid=1000 Gid=1000 Pid=17137] "security.selinux" 255 @0
-> [ID=0x8] Getxattr error=operation not supported
<- Lookup [ID=0xa Node=0x1 Uid=1000 Gid=1000 Pid=17137] "sub"
-> [ID=0xa] Lookup 0x3 gen=0 valid=1s attr={valid=1s ino=5826373571668926310 size=0 mode=drwxr-xr-x}
# sub is node 3, not node 2

<- Forget [ID=0xc Node=0x3 Uid=0 Gid=0 Pid=0] 1
-> [ID=0xc] Forget
<- Lookup [ID=0xe Node=0x1 Uid=1000 Gid=1000 Pid=17137] "sub"
-> [ID=0xe] Lookup 0x3 gen=1 valid=1s attr={valid=1s ino=5826373571668926310 size=0 mode=drwxr-xr-x}
<- Getxattr [ID=0x10 Node=0x3 Uid=1000 Gid=1000 Pid=17137] "system.posix_acl_access" 0 @0
-> [ID=0x10] Getxattr error=operation not supported
<- Forget [ID=0x12 Node=0x2 Uid=0 Gid=0 Pid=0] 1
-> [ID=0x12] Forget
```

In rclone cmd/mount/dir.go:

```
	case *vfs.File:
		return &File{x}, nil
	case *vfs.Dir:
		return &Dir{x}, nil
```

You need to return nodes that are equal to the previous response, to have them be the same node. With this code, every time a node is looked up, it's a branch new node with no relation to existing filesystem content -> observed behavior is exactly what was asked for.

**Comment by tv42** [comment]
Oh, and a (quite complex) example of doing it mostly right is in bazil.org/bazil, basically the dir keeps a field `active [string]blah` that knows active child nodes (lifespan from Lookup/Create/Mkdir/etc to Forget), and uses that to handle repeat Lookups. In bazil's case that's complicated by the fact that it also has non-kernel consumers, and so there's a refcount for that too, with the kernel-alive part stored in a bool.

**Comment by ncw** [comment]
Thank you very much for working through this. I'm sorry it turned out to be a bug in rclone's code but I'm really grateful for the help - I don't think I would have got there on my own.

**Comment by tv42** [comment]
I wish this whole thing was better documented, but at the same time it's a lot writing, and much of it is about things outside this Go library.

**Comment by ncw** [comment]
Yes better documentation would be great! Trying to debug FUSE stuff inevitably ends up with grepping the kernel source or the libfuse source...

If you write a book about it I'll buy it :-)

**Comment by ncw** [comment]
I can confirm that modifying things to make sure we always return the same node instead of re-creating it fixes the problem :+1:
