### ISSUE TITLE
Support older FUSE protocol versions, for old SuSE systems

### ISSUE THREAD

**Issue by HeikoSchlittermann** [bazil/fuse#251]
Hi, after building an application using bazil/fuse, we run into trouble on an older SuSE system. They support protocol version 7.16, while bazil/fuse asks for 7.17.

If I have a look at the commit that bumped the protoVersion*Minor, than I *think*, this should be backward compatible and work with older kernels (7.16) too.
Simple practical checks indicate, that the application is still working after setting the protoVersionMinMinor forcefully to 16.

Shouldn't the min/max be a range, rather than a point?

What is the official way to support both older versions of the kernel module?

**Comment by tv42** [comment]
It would be possible to support older versions, but I would personally much rather push forward not backward. We're already far behind what the kernel actually can do (because osx support dragged us backward).

**Comment by tv42** [comment]
This is simply too much effort, to keep maintaining all the code branches from all the old protocol versions. Personally, I will prioritize new features over accommodating outdated enterprise distributions. At least up until a corporate sponsor tells me legacy SuSE releases are important to them.
