### ISSUE TITLE
fuse.AsyncRead() not worked on Mac os

### ISSUE THREAD

**Issue by hunjixin** [bazil/fuse#253]
fuse.AsyncRead() not worked, receive read request  one by one, how can i  receive many request?

os: mac 10.14.6

**Comment by hunjixin** [comment]
@tv42

**Comment by tv42** [comment]
The docstring is probably wrong, that's not exactly what it does.

**Comment by hunjixin** [comment]
> The docstring is probably wrong, that's not exactly what it does.

work as expected in centos,  receive read request almost  in the same time. maybe not support on mac os

**Comment by tv42** [comment]
Since I dropped macOS support for lack of open source future on that platform, closing this issue too.
