### ISSUE TITLE
Study course

### ISSUE THREAD

**Issue by CoolRao** [bazil/fuse#258]
There are too few cases, how to create files, are there any examples?
There are communication groups？

**Comment by tv42** [comment]
Have you tried https://github.com/bazil/bolt-mount & https://eagain.net/talks/bolt-mount/ or https://github.com/bazil/zipfs ?

You are required to understand Linux filesystems and FUSE to implement a Linux filesystem with FUSE. This Go library is not the right place to document the Linux filesystem interface or FUSE. I don't have the free time to write that from scratch, and if I did, it would end up being a book not a copy-paste example.
