### ISSUE TITLE
os.Mode() does not align to fuse.DirentType

### ISSUE THREAD

**Issue by KyleSanderson** [bazil/fuse#260]
hmm. I'm a bit puzzled why these definitions don't align between the implementations when they're pure golang. Golang has defined these bits as stable cross platform (across every single OS that is supported with golang), but some-how we have an invented type in Bazil that is not compatible between the native construct. Can you please clarify why this is the case - and perhaps a compatibility layer between the two?

**Comment by tv42** [comment]
"Native" for FUSE is the FUSE protocol. The first priority is being able to express things that are used in the FUSE protocol. Directory entry is not the same as stat(2) response, for example DT_Unknown.

Compare https://www.man7.org/linux/man-pages/man2/getdents.2.html  
vs https://www.man7.org/linux/man-pages/man2/lstat.2.html
