### ISSUE TITLE
 "ToErrno" is un man-friendly for os.PathErr

### ISSUE THREAD

**Issue by xzy256** [bazil/fuse#262]
Some scenes,  func `handleRequest` return a `os.PathErr`,  then call `done` handle error, finally got a `DefaultErrno  (EIO)`  error after `ToErrno` called. It's so Confused. Such as `permission denied` pathErr should be showed,  but showing 'Input/output error'
Why shouldn't pass error directly?

a example scene: 
`ls` a directory with `644` mode 

![20201021192708](https://user-images.githubusercontent.com/22289078/96713703-9728e900-13d3-11eb-9377-c8e8915823ea.png)

**Comment by tv42** [comment]
As per the docs https://godoc.org/bazil.org/fuse#ToErrno

> If the underlying type of err is syscall.Errno, it is used directly. No unwrapping is done, to prevent wrong errors from leaking via e.g. *os.PathError.

This is intentional. Imagine a filesystem that stores all metadata in a local database; being unable to open that database doesn't mean that all files don't exist / are unreadable / etc.

If you have are writing a filesystem that 1:1 maps FUSE operations to backing filesystem operations, you can trivially unwrap that `os.PathError`. That's doesn't make it generally the right thing to do.

**Comment by xzy256** [comment]
Thanks for  your explanation. Mybay that 1:1 maps is not obvious , but i still think some `KnownOsErr` should be wraped，so third part can show man-friendly message rather than `input/output error`.  Such as my implementation
```go
func ToErrno(err error) Errno {
	if err, ok := err.(syscall.Errno); ok {
		  return Errno(err)
	 }
	var errnum ErrorNumber
	if errors.As(err, &errnum) {
	         return Errno(errnum.Errno())
	}
+	return handleKnownOsErr(err)
+}
+
+
+var err2no = map[Errno]string {
+	EACCES:		 "permission denied",
+}
+
+func handleKnownOsErr(err error) Errno {
+	switch er := err.(type) {
+	case *os.PathError:
+		if er.Err.Error() == err2no[EACCES]  {
+			return EACCES
+		}
+		break
+	case *os.LinkError:
+	case *os.SyscallError:
+	}
+
	return DefaultErrno
}
```

**Comment by tv42** [comment]
I have no intent of unwrapping `*os.PathError` errors from Node/Handle methods. Those errors are internal details. That would make code like `cfg, err := n.loadConfig(); if err != nil { return nil, err }` do the wrong thing.

For the accesses where you are specifically accessing some backing filesystem, with 1:1 files, you can unwrap errors easily yourself -- and even in that filesystem implementation, that should only be done for the operations actually touching the backing filesystem, not all errors.

**Comment by xzy256** [comment]
ok,  thank you all the same
