### ISSUE TITLE
Go Get fails

### ISSUE THREAD

**Issue by knusbaum** [bazil/fuse#263]
Maybe I'm doing something wrong, but I'm not sure what...
```
go get -u bazil.org/fuse@latest
go: golang.org/x/sys upgrade => v0.0.0-20201020230747-6e5568b54d1a
# bazil.org/fuse
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/error_std.go:26:20: undefined: errNoXattr
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:171:12: undefined: mount
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:236:24: undefined: maxWrite
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:425:32: undefined: maxWrite
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:810:12: undefined: openFlags
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:828:18: undefined: openFlags
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:845:18: undefined: openFlags
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:868:18: undefined: openFlags
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:991:12: undefined: openFlags
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:1413:20: undefined: maxWrite
../../../../../../go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fuse.go:1413:20: too many errors
```

**Comment by tv42** [comment]
What platform? What does `go env GOOS GOARCH` say?

**Comment by knusbaum** [comment]
Ahh, sorry I didn't provide enough info. I'm on OS X
```
$ go env GOOS GOARCH
darwin
amd64
```

MacFUSE is installed, but I didn't consider that this library may not work with it.

**Comment by tv42** [comment]
macOS does not have an up to date open source FUSE implementation. https://github.com/bazil/fuse/issues/224

**Comment by susarlanikhilesh** [comment]
$ go get bazil.org/fuse
# bazil.org/fuse
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\error_std.go:26:20: undefined: errNoXattr
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse.go:425:32: undefined: maxWrite
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse_kernel.go:185:28: undefined: syscall.O_DIRECTORY
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse_kernel.go:194:38: undefined: syscall.O_ACCMODE
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse_kernel.go:695:24: undefined: unix.F_RDLCK
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse_kernel.go:696:24: undefined: unix.F_WRLCK
..\..\..\..\pkg\mod\bazil.org\fuse@v0.0.0-20200524192727-fb710f7dfd05\fuse_kernel.go:697:24: undefined: unix.F_UNLCK



 go env GOOS GOARCH
windows
amd64


I'm also getting the same issue. Is it not supported on this platform too ?


Thank you

**Comment by tv42** [comment]
@susarlanikhilesh Windows has never had any kind of real FUSE compatibility. It's wildly different.
