### ISSUE TITLE
fuse.mount exit status 1 MacOS Catalina 10.15.5

### ISSUE THREAD

**Issue by hykych** [bazil/fuse#267]
OXSFUFSE version: 3.10.4
bazil/fuse version: v0.0.0-20180421153158-65cc252bf669

It had ran successfully before, but suddenly it return a error: exit status 1
mountpoint = "/tmp/fuse",  fstype="fs"
```
c, err := fuse.Mount(  
		mountpoint,  
		fuse.FSName(fstype),  
		fuse.Subtype(fstype),  
		fuse.LocalVolume(),
		fuse.VolumeName(fstype),
		fuse.NoAppleDouble(),
		fuse.NoAppleXattr(),
	)
```

**Comment by tv42** [comment]
macOS does not have an up to date open source FUSE implementation.

Go does not provide a clean way to annotate supported platforms.

See https://github.com/bazil/fuse/issues/224
