### ISSUE TITLE
How to read dir use read not readall

### ISSUE THREAD

**Issue by chutingxia** [bazil/fuse#269]
when i do HanderReadRequest, i want to read dir ,but i only can use HandleReadDirAller, can i use HandleReader like read a file  as my dir is too large

**Comment by tv42** [comment]
Stop spamming the issues. Only ReadDirAll is implemented.

**Comment by tv42** [comment]
Duplicate of https://github.com/bazil/fuse/issues/58

**Comment by chutingxia** [comment]
thank you , i get it!
