### ISSUE TITLE
syntax error: unexpected o777

### ISSUE THREAD

**Issue by m-amir-ir** [bazil/fuse#272]
Hello Dear contributors 
when I want to compile a application with dependency with fuse . I have problem with these errors:
vendor/bazil.org/fuse/fuse.go:498:34: syntax error: unexpected o777, expecting comma or )
vendor/bazil.org/fuse/fuse.go:1530:31: syntax error: unexpected o777 at end of statement

my OS is ubuntu 18.04 and my go version go1.11 linux/amd64

**Comment by kos-v** [comment]
@m-amir-ir Support for new syntax of octal literals was added in go13.0.
It looks like the library doesn't support older versions of go: https://github.com/bazil/fuse/blob/master/go.mod
https://github.com/bazil/fuse/commit/bc934ca1905c8bf314c599badc1eaeafc92dd494

**Comment by tv42** [comment]
go1.11 is *ancient* and has known security & data corruption bugs. You need to upgrade. You needed to upgrade many years ago already.
