### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by Woellchen** [bazil/fuse#277]
hey there!
i was surprised to see that macos support was dropped. was there any specific reason for it? i could not find anything to this with a quick search
locally i am using this library on my mac with some patches for the current osxfuse version, and for my use cases it is working fine. would it help if i submitted this patch as a pr?
thank you :)

**Comment by tv42** [comment]
macOS does not have an up to date open source FUSE implementation.

Go does not provide a clean way to annotate supported platforms.

https://github.com/bazil/fuse/issues/224  
https://github.com/bazil/fuse/issues?q=is%3Aissue+label%3Aplatform%3Aosx
