### ISSUE TITLE
go build hello.go  is error

### ISSUE THREAD

**Issue by clevertension** [bazil/fuse#281]
MacOS 10.15.7 

go build hello.go 
# bazil.org/fuse
../../error_std.go:26:20: undefined: errNoXattr
../../fuse.go:171:12: undefined: mount
../../fuse.go:236:24: undefined: maxWrite
../../fuse.go:425:32: undefined: maxWrite
../../fuse.go:810:12: undefined: openFlags
../../fuse.go:828:18: undefined: openFlags
../../fuse.go:845:18: undefined: openFlags
../../fuse.go:868:18: undefined: openFlags
../../fuse.go:991:12: undefined: openFlags
../../fuse.go:1413:20: undefined: maxWrite
../../fuse.go:1413:20: too many errors

**Comment by tv42** [comment]
macOS does not have an up to date open source FUSE implementation.

Go does not provide a clean way to annotate supported platforms.

#224
https://github.com/bazil/fuse/issues?q=is%3Aissue+label%3Aplatform%3Aosx
