### ISSUE TITLE
mknod request is not received

### ISSUE THREAD

**Issue by chrislusf** [bazil/fuse#282]
When mounting, I specified the option `fuse.AllowDev()`.

When running pjdfstest, `mknod` request is not received by the fuse mount on linux (or Mac).

```
$ prove -rv /Users/chrislu/dev/pjdfstest/tests/chmod/my.t
/Users/chrislu/dev/pjdfstest/tests/chmod/my.t ..
1..5
ok 1
not ok 2 - tried 'mknod n0/n1 b 0644 1 2', expected 0, got EPERM
not ok 3 - tried 'chmod n0/n1/test 0644', expected ENOTDIR, got ENOENT
not ok 4 - tried 'unlink n0/n1', expected 0, got ENOENT
ok 5
Failed 3/5 subtests
```

I customized the test file content a bit, to only test block devices:
```
#!/bin/sh
# vim: filetype=sh noexpandtab ts=8 sw=8
# $FreeBSD: head/tools/regression/pjdfstest/tests/chmod/01.t 211474 2010-08-18 22:06:43Z pjd $

desc="chmod returns ENOTDIR if a component of the path prefix is not a directory"

dir=`dirname $0`
. ${dir}/../misc.sh

echo "1..5"

n0="n0"
n1="n1"

expect 0 mkdir ${n0} 0755
for type in block; do
	create_file ${type} ${n0}/${n1}
	expect ENOTDIR chmod ${n0}/${n1}/test 0644
	expect 0 unlink ${n0}/${n1}
done
expect 0 rmdir ${n0}

```

**Comment by chrislusf** [comment]
The `Mknod` is also implemented. https://github.com/chrislusf/seaweedfs/blob/master/weed/filesys/dir.go#L169

btw: The source code is using an older version of `github.com/bazil`.

**Comment by tv42** [comment]
Is the filesystem client running as root? I doubt any sane kernel will let non-root `mknod(2)` ever reach a filesystem.

Mknod has a test and passes just fine.

```
doas ./fs.test -test.v -test.run=Mknod
=== RUN   TestMknod
    serve.go:923: FUSE: <- Lookup [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=1639711] "node"
    serve.go:982: FUSE: -> [ID=0x4] Lookup error=ENOENT
    serve.go:923: FUSE: <- Mknod [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=1639711] Name "node" mode=prw-r----- umask=-----w--w- rdev=0
    serve.go:982: FUSE: -> [ID=0x6] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=14080586109597528000 size=0 mode=prw-rw-rw-}
--- PASS: TestMknod (0.00s)
PASS
```

**Comment by chrislusf** [comment]
Thanks for the pointer. I did not run it as root, but also get the same result.

do I need to use `fuse.AllowRoot()` also?

**Comment by tv42** [comment]
AllowRoot was a red herring caused by the C libfuse having no clean boundaries in its design ([1](https://github.com/bazil/fuse/commit/e0b89709bc6481f1345b6e19363cf18766e53fc7)), you mean [AllowOther](https://pkg.go.dev/bazil.org/fuse#AllowOther).

Most likely yes. The test runs both the server and the client as root, so it's exempt from needing AllowOther.

**Comment by chrislusf** [comment]
Thanks for the help again! I figured it out following your tips!

I need to:
* Mount the directory via fuse as root, without enabling `fuse.AllowOther()`.
* Use the mounted directory also as root, just because the mounted directory is not accessible by any other user.

**Comment by tv42** [comment]
libfuse is, as a whole, completely undocumented and frankly simply bad code. It makes no distinction on features and capabilities of kernel, FUSE protocol, and the C library. One of my guiding principles on this project has been to read the kernel source only, ignoring libfuse.
