### ISSUE TITLE
Closing the FUSE connection

### ISSUE THREAD

**Issue by benbjohnson** [bazil/fuse#287]
What is the correct way to unmount a FUSE directory? I tried using `fuse.Conn.Close()` but [it requires a  `rio` write lock](https://github.com/bazil/fuse/blob/fb710f7dfd05053a3bc9516dd5a7a8f84ead8aab/fuse.go#L552). I find that `fuse.Conn.ReadRequest()` usually [has a read lock when it's waiting for data](https://github.com/bazil/fuse/blob/fb710f7dfd05053a3bc9516dd5a7a8f84ead8aab/fuse.go#L579-L581).

I tried calling `fuse.Unmount()` but that returns a `fusermount: failed to unmount /litefs/data: Device or resource busy` error if the connection is still open.

Should the `ReadRequest()` obtain the `fd` under lock first and then call `syscall.Read()` without the lock?

```go
c.rio.RLock()
fd := c.fd()
c.rio.RUnlock()

n, err := syscall.Read(fd, m.buf)
```

**Comment by tv42** [comment]
The only thing I know of (on Linux) is calling the external `fusermount` binary, which is .. messy.

It seems your mountpoint is still in use. No mounts can be unmounted if they're busy; that's like asking to free a chunk of memory with pointers to it.

I believe closing the /dev/fuse FD (while the FS is still mounted) will be equivalent to your program crashing -> mount point stays in broken state.

**Comment by benbjohnson** [comment]
Thanks, @tv42. There's a child application that I'm closing first before unmounting so I'd be surprised if there were open connections but I'll try to dig in further and see if I can tell what's holding on. Is calling `fuse.Conn.Close()` the right way to shut down? Anything else I should do?

**Comment by tv42** [comment]
You want to use `fusermount -u` or `fuse.Unmount` and let the unmount complete (kernel may send a few messages, then *it* closes the `/dev/fuse` FD). That'll make `fs.Serve` wait for concurrent handlers, then return.

To see who's keeping the mount busy, `lsof /my/mount/point` is your friend. Run as root to see other users. Beware filesystem namespaces making everything confusing.
