### ISSUE TITLE
Guys, can someone explain how can I write something on a disk normally?

### ISSUE THREAD

**Issue by nemesidaa** [bazil/fuse#305]
I tried to build my own system via os or sys library, but it also sends me IO error. I want to make just a wrapper to kernel fs(mine is ext4, if it needed), but after some tries the only right things I see is to allocate new directory and work with that to write something, or use in-memory allocations. I really will glad to see any, let it be the simpliest examples of the code, or even just the other repos realised that. Early thanks.

**Comment by tv42** [comment]
There's absolutely nothing actionable here, you're not even asking a question that *can* be answered, you're just asking someone else to write your program for you. That's not how the world works.

FUSE lets you write a Linux filesystem in userspace. If you, in your filesystem implementation, want to use another filesystem, just do that -- open files, read and write data. Your FS methods get called to access and manipulate files in your FUSE filesystem, you implement those in ways that store the data where you want, how you want.

You are still required to understand what Linux filesystems are and how they work, FUSE merely makes it possible to write them *in userspace*.

I have some sketches of more introductory material I've been working on, but the effort required there is essentially writing a harder-than-typical technical book, and that's not something that gets whipped together in a weekend, even if it was my highest-priority project (which it isn't).

Feel free to continue replying to this issue, but please try to ask a question that can plausibly be answered with less than 15 minutes of work.
