### ISSUE TITLE
upgrade FUSE protocol version

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#33]
Protocol changelog: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/fuse.h#n38

- OSXFUSE is still at 7.8, would need lots of conditionals in code for backwards compat
  - https://github.com/osxfuse/kext master (to be 3.x) is now up to 7.19, but not released
  - https://github.com/osxfuse/osxfuse/issues/155 is asking for a new OSXFUSE release

**Comment by jacobsa** [comment]
Shot in the dark, since I came across this thread while Googling: I'm finding that on Linux 3.19.0-15-generic with fuse protocol 7.23, my file system is immediately unmounted after responding to Init. In contrast, on 3.13.0-52-generic with 7.22, that doesn't happen. Any idea what might cause this?

**Comment by jacobsa** [comment]
Sorry, I think my newer system was just misconfigured. Please ignore me.

**Comment by tv42** [comment]
Finally got around to this. The conditional code wasn't too bad, though it needed a bunch of refactoring to make it possible.

Fixed in multiple commits around cbef07cc6370d0c135cc8b95eeacc4e40d8fd0fa.
