### ISSUE TITLE
notify kernel of stale files [depends:#33]

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#34]
depends: #33

Needed so filesystems can bring in external updates, e.g. sshfs noticing remote changes.

**Comment by tv42** [comment]
Fixed in f58cb5f640bfbbc6d91538777262860c75de6160 & 71962e0a911499fb84a02c9d973274de1c1c3a4b.

**Comment by trevordixon** [comment]
If I understand correctly, this doesn't work on OS X, because the stable OSXFUSE only supports an old protocol still, right? But the pre-release builds from https://github.com/osxfuse/osxfuse/releases do support this feature?

**Comment by tv42** [comment]
@trevordixon OSXFUSE 3.x should support the feature. OSXFUSE 3.x also hard crashes my mac too often to really test it much. If you can, please help the OSXFUSE upstream in any way you can.
