### ISSUE TITLE
OS X .Trashes items do not see Remove when emptying trash

### ISSUE THREAD

**Issue by ryanstout** [bazil/fuse#40]
Ok, so feel free to say this it outside of the scope of bazil/fuse, but I've got my file system working and I added -o local,... to mount_darwin.go to run the file system locally.  On osx when I drag a file to the trash, it goes to a .Trashes folder on the file system.  (I can even restore fine)  The weird thing though is that when I empty the trash, I don't get any Remove or Rename's.  Any idea what OSX does when you clear the trash on a local file system?  The files just stay there and the trash bin shows full.  I'm just wondering if anyone has any ideas on this?  Thanks!

**Comment by ztalbot2000** [comment]
I have replicated this issue exactly.  There are two errors.  The last is because when the mount failed, the mount point was trying to be moved to .Trash, but root does not have a .Trash directory. The .Trash directory is created when you log in via the main login screen. Something never done by root.
  The first error was the mount failure.  If you use dd to image Raspbian to an SD card and then try to mount it right away the mount fails because the filesystem is not ext2/3/4 but squashfs. Hence trying to put the mount point in the .Trash.
This explains every aspect and if the problem is still open, it should be closed.

**Comment by ztalbot2000** [comment]
Here is my log.  Look familiar?  

udo /Volumes/crosstoolBase/brew/bin/fuse-ext2 -v /dev/disk3s2  ./linux -o debug
Password:
Mounting /dev/disk3s2 Read-Only.
Use 'force' or 'rw+' options to enable Read-Write mode
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 24022
INIT: 7.19
flags=0xf8000008
max_readahead=0x00100000
   INIT: 7.19
   flags=0x00000010
   max_readahead=0x00100000
   max_write=0x02000000
   max_background=0
   congestion_threshold=0
   unique: 2, success, outsize: 40
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 123
getattr /
   unique: 2, success, outsize: 136
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 0
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 123
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 123
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 123
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 60
LOOKUP /.fseventsd
getattr /.fseventsd
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 197
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 325
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 733
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 732
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 875
getattr /
   unique: 2, success, outsize: 136
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 875
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 197
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 325
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 732
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 733
statfs /
   unique: 3, success, outsize: 96
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 3, success, outsize: 48
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 2, success, outsize: 48
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 876
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 3, success, outsize: 48
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 876
LOOKUP /.localized
getattr /.localized
   unique: 2, error: -2 (No such file or directory), outsize: 16
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 876
LOOKUP /.localized
getattr /.localized
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 2, error: -45 (Operation not supported), outsize: 16
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 197
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 325
statfs /
   unique: 2, success, outsize: 96
unique: 3, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 876
getattr /
   unique: 3, success, outsize: 136
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 2, success, outsize: 48
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 3, error: -45 (Operation not supported), outsize: 16
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 2, error: -45 (Operation not supported), outsize: 16
unique: 3, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 732
statfs /
   unique: 3, success, outsize: 96
unique: 2, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 733
statfs /
   unique: 2, success, outsize: 96
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 2, success, outsize: 48
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 3, error: -45 (Operation not supported), outsize: 16
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 2, error: -45 (Operation not supported), outsize: 16
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 77, pid: 876
getxattr / com.apple.FinderInfo 32 0
   unique: 3, success, outsize: 48
unique: 2, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 2, error: -45 (Operation not supported), outsize: 16
unique: 3, opcode: GETXATTR (22), nodeid: 1, insize: 92, pid: 876
getxattr / com.apple.metadata:_kMDItemUserTags 0 0
   unique: 3, error: -45 (Operation not supported), outsize: 16
^Cunique: 2, opcode: DESTROY (38), nodeid: 1, insize: 40, pid: 24054
   unique: 2, success, outsize: 16


Based on what I was doing it puts my previous explanation into context.  
Mounting a squashfs with fuse will reproduce the first mount error and the subsequent error  of trying to put the failed mount point into the .Trash, which root does not have.

**Comment by tv42** [comment]
The original problem was that the reporter claimed to not see any FUSE activity when he emptied the trash. (Still waiting for details.) I don't see how you talking about `.Trash` not existing has anything to do with that.

**Comment by tv42** [comment]
Heads up: the future of macOS support is in danger. If you care about FUSE on macOS, please encourage talented developers to pick up maintenance of the open source project. See https://github.com/bazil/fuse/issues/224

**Comment by tv42** [comment]
Can't do anything here.

Tagged as doc because of the braindump of macOS trash behavior in https://github.com/bazil/fuse/issues/40#issuecomment-55051510 -- it'd be nice of some macOS people wrote up all the oddities of Finder etc, and .Trash and the xattr kludge would be part of that.
