### ISSUE TITLE
Support `novncache` for disabling OSXFUSE dirent caching

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#81]
https://github.com/osxfuse/osxfuse/issues/199
"The entry_valid field is currently ignored by osxfuse."

https://code.google.com/p/macfuse/wiki/OPTIONS

Request in https://github.com/bazillion/fuse/issues/77#issuecomment-82660544

**Comment by jdoliner** [comment]
Any word on this? Would be really useful for me?

Alternately it might be nice to have something like:

```
func FlagOption(key string, value string) MountOption {
    return func(conf *mountConf) {
         conf.options[key] = value
    }
}
```

so that users can easily add their own flags without needing each one to be statically defined

**Comment by tv42** [comment]
Heads up: the future of macOS support is in danger. If you care about FUSE on macOS, please encourage talented developers to pick up maintenance of the open source project. See https://github.com/bazil/fuse/issues/224

**Comment by tv42** [comment]
macOS support has been removed. If somebody wants to pick up maintaining an open source macOS FUSE, or wants to fund supporting the proprietary continuation of OSXFUSE, please get in touch.
https://github.com/bazil/fuse/issues/224
