### ISSUE TITLE
Missing FUSE helpers

### ISSUE THREAD

**Issue by anacrolix** [bazil/fuse#85]
If FUSE is unavailable, it would be nice to have some way to determine that this is the cause for mount errors as it varies by platform. Something like the "os"-package-style `func IsMissingFuseError(error) bool`, or a another function like `func FuseAvailable() bool`.

For context, this is what I currently get on some tests, I want to skip them if FUSE isn't available:

```
anacrolix@Matts-MBP:~/gopath/src/github.com/anacrolix/torrent$ go test ./fs
/Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
--- FAIL: TestUnmountWedged (0.23s)
    torrentfs_test.go:111: error mounting: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20801f6c0)}
```

The osxfusefs.kext line I think is written out of band by fusermount most likely, and the ExitError is given to me from `fuse.Mount`.

**Comment by w-vi** [comment]
:+1: for this feature, I'm in similar situation

**Comment by tv42** [comment]
That looks like you actually have osxfuse installed, because it got that far.

There's just a lot of different things that could go wrong, and I don't really have a comprehensive catalog of them..

**Comment by anacrolix** [comment]
As an example, loadOSXFUSE in mount() in mount_darwin.go.

**Comment by tv42** [comment]
Sure, but wrong how? Especially the case you have above -- the binary exists, but running it produces some output and an exit status -- could mean many things.

**Comment by tv42** [comment]
macOS support has been removed. If somebody wants to pick up maintaining an open source macOS FUSE, or wants to fund supporting the proprietary continuation of OSXFUSE, please get in touch.
https://github.com/bazil/fuse/issues/224
