### ISSUE TITLE
Locking Support?

### ISSUE THREAD

**Issue by creiht** [bazil/fuse#86]
The F_GETLK, F_SETLK, and F_SETLKW requests are currently not implemented.  Are there plans to expose these through the interface?

Thanks!
## 

Chuck

**Comment by tv42** [comment]
I would absolutely welcome a contribution implementing them! I haven't had that need yet, personally. It's a worthwhile feature, but the backlog is large.

It's also worth noting that locking *on one host* works without the FUSE filesystem doing anything special. The locks needs to be served through FUSE only when you want to e.g. coordinate network-wide, in a network filesystem.

**Comment by creiht** [comment]
Yeah, I will need the feature for an experiment, and will look at adding it in when I get to that point.

**Comment by tv42** [comment]
Notes for later: remember to use lkInSize, understand InitPosixLocks.

**Comment by tv42** [comment]
I looked into locks, they look very much doable and reasonable, but enabling them requires a protocol bump and that brings in other features that must be implemented first.
