### ISSUE TITLE
Combining fuse.OpenNonSeekable, page cache, and short reads causes re-reads of same offset

### ISSUE THREAD

**Issue by mpictor** [bazil/fuse#88]
I'm using bazil/zipfs as the basis for a fuse+http filesystem, and noticed data corruption. I started printing various things in the zipfs function [`func (fh *FileHandle) Read(...)`](https://github.com/bazil/zipfs/blob/master/main.go#L208) and noticed that sometimes there are two sequential Read's where req.Offset does not change.

This seems like a bug, but I'm not certain that it is in bazil/fuse. This behavior definitely does _not_  match the comments at [zipfs/main.go:189](https://github.com/bazil/zipfs/blob/master/main.go#L189) or [zipfs/main.go:212](https://github.com/bazil/zipfs/blob/master/main.go#L212).

I'm creating the issue here since it seems like the issue affects more than bazil/zipfs.

**Comment by tv42** [comment]
Can you tell more about both your environment (Linux? OS X?) and the filesystem actions that resulted in two reads with the same offset?

**Comment by mpictor** [comment]
This is on Linux. I triggered the behavior with both `cp` and `dd`.

After more investigation, it seems that the important factor was that on the first call ~2.5kb was placed in the buffer, in spite of the program requesting more. `dd` requested 4k, and I'm not sure about `cp`.

When the buffer wasn't full, the call would be repeated with identical offset and size, and this time the buffer would be filled.

----
If you have trouble replicating this, I suspect I was getting this behavior because `Read` was reading directly from an `http.Request.Body`. I'm assuming that the partially filled buffer was due to some data still being on the wire, and the `Read` method opting to copy what it had rather than blocking.

Adding an intermediate step of copying the data to a `bytes.Buffer` has caused the problem to go away, at least so far.

**Comment by tv42** [comment]
Oh yes, when you let the kernel page cache do caching, it always reads and writes full blocks (last block of the file may be partial). So if it wants to read, to get the rest, it'll just read the same block again.

You don't need the in-memory copy in between, as long as you do `io.ReadFull` or such (if you use that, pay attention to handling `ErrUnexpectedEOF`  properly).

If you for some reason can't have that, then you need to disable the kernel page cache, with `fuse.OpenDirectIO`. That may or may not make sense for your use case.

For the record, I tested and `os.File.Seek` with `fuse.OpenNonSeekable` in effect gives `illegal seek` errors. Leaving this bug open at least as long as I don't have a unit test for that, though.

**Comment by tv42** [comment]
Ideas and/or patches for improving documentation are very much welcome!

**Comment by tv42** [comment]
Since this is "just" waiting for better documentation, I'm going to go ahead and close it. All closed issues with type:doc are input for better documentation, there's no need to keep this open.
