### ISSUE TITLE
Unexport InitRequest, InitResponse, and InitFlags

### ISSUE THREAD

**Issue by jacobsa** [bazil/fuse#95]
As far as I can tell, as of 3ad48988b4b4b0a10aba0a4043dbd2a90e3e0e02 InitFlags, InitRequest, and InitResponse are no longer useful to clients. Should they be unexported?

That will of course cause users to no longer compile, but as a user I would prefer that to a silent change in functionality. Having them exported is also confusing, because they look like I might need to care about them.

**Comment by tv42** [comment]
Yes, that is true. I'm holding off on the unexporting until I'm sure I won't need to add some sort of a generic Init callback function as a MountOption (that would, once again, need these types). Once it's clear that people's use cases can be covered with simpler MountOptions, these types will be unexported -- right now, I just want to minimize churn, there's enough of that already.
