### ISSUE TITLE
Add a mount option for InitResponse.MaxWrite

### ISSUE THREAD

**Issue by jacobsa** [bazil/fuse#96]
I see that after the API change in 3ad48988b4b4b0a10aba0a4043dbd2a90e3e0e02, InitResponse.MaxReadahead became a mount option. I would like to continue setting MaxWrite, since the default of 4 KiB is crazy small. Can that be made into a mount option, too?

**Comment by jacobsa** [comment]
Ah, I see that [you're already setting this](https://github.com/bazil/fuse/blob/bfad7b76956fce4d4588ed9a7122e187ccd1e0a2/fuse.go#L215-L216) on my behalf, to the largest value that I've seen work in Linux. Sounds good to me.

**Comment by tv42** [comment]
Yes, and MaxWrite is very closely tied to the buffer management in the library anyway, so it's best to let that part run the show. This setting is easy to have on always, and larger values make no difference, so I didn't see value in configurability.. but now that FSIniter is gone, we could actually even do that, if a reason for it appeared. Before, it was a chicken-and-egg problem.

**Comment by jacobsa** [comment]
Sounds good; I'm happy as long as you choose a large value.

**Comment by tv42** [comment]
Just for the record, the intent for all defaults in bazil.org/fuse is "maximum performance that doesn't cause surprising behavior".

For example, I'll happily max out read/write sizes and claim your code should just handle the `[]byte` it gets, where as I would never set `InitNoOpenSupport` by default as that changes the whole dialog around nodes & handles; that deserves a `MountOption` (which will be added once I've tested that it actually works).

Whether writeback caches and readahead are too surprising to be default or not is something I still haven't formed a clear opinion on.

**Comment by jacobsa** [comment]
Agreed on the philosophy, yeah. I would personally say that you should go for writeback caches and readahead by default, but consider options to turn them off if they are a problem for somebody.
